"""Prospective rank/width study with development and fresh-data release barriers.

Run as a package module, including inside an immutable ``source`` snapshot.
Training workers receive observed arrays only; private teacher specifications
are generated by the coordinator and are never loaded by a fitting function.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import multiprocessing
import time
import traceback
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import asdict
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path

import numpy as np
import torch

from . import (
    rank_initialization_v2 as initializer,
    rank_learning as base,
    rank_orthogonal_v2 as optimizer,
    rank_width_learning as width,
    rank_width_tasks as tasks,
)


def now():
    return datetime.now(timezone.utc).isoformat()


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def read(path):
    return json.loads(Path(path).read_text())


def write(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x") as stream:
        json.dump(value, stream, indent=2, allow_nan=False)
        stream.write("\n")


def configuration(confirmation_teachers=4):
    if confirmation_teachers not in (4, 8):
        raise ValueError("Timing-only rule must select four or eight fresh teachers")
    return {
        "schema": "rank_width_v1",
        "tasks": ["mixture_q1", "mixture_q2", "quadratic_q2"],
        "geometries": list(width.GEOMETRIES),
        "families": ["shunt", "relu", "tanh"],
        "development_teachers": [10, 11],
        "confirmation_teachers": list(range(30, 30 + confirmation_teachers)),
        "teacher_seed_base": 2026105001,
        "observation_seed_base": 2026119001,
        "model_seed_base": 2026121001,
        "main_n": 2048,
        "validation_n": 2048,
        "test_n": 8192,
        "calibration_p": [245, 965],
        "bridge_p": 485,
        "withheld_p": 1925,
        "primary_p": [245, 485, 965, 1925],
        "stages": 3,
        "steps": 150,
        "log_risk_threshold": 1e-18,
        "expected_fits": 890 + 360 * confirmation_teachers,
        "fit_counts": {
            "diagnostic": 80,
            "development": 720,
            "bridge": 90,
            "confirmation": 360 * confirmation_teachers,
        },
        "scope": "Previously studied mixture teachers10/11 with new observations are development only. Fresh teachers30+ are inference units; two observations per teacher. Quadratic teachers vary orientation only. All primitives/geometries and all outcomes retained. Width2/4 evade the one-accessible-projection floor. No asymptotic learned exponent or universal dendritic advantage is assumed.",
    }


def choices(config):
    return [
        {
            "id": f"{method}_ridge{ridge:.0e}",
            "method": method,
            "fit": asdict(
                base.FitConfig(
                    ridge=ridge,
                    steps=config["steps"],
                    learning_rate=0.5,
                    objective_scale=1e4,
                    tolerance_grad=1e-10,
                    tolerance_change=1e-14,
                    history_size=30,
                )
            ),
        }
        for method, ridge in itertools.product(["ols", "stein"], [1e-8, 1e-5])
    ]


def verify(root):
    receipt = read(root / "initialized.json")
    for name, digest in receipt["bindings"].items():
        if sha(root / name) != digest:
            raise ValueError(f"Frozen file changed: {name}")
    return receipt


def verify_selection(root):
    verify(root)
    receipt = read(root / "selection_complete.json")
    if sha(root / "selected_recipes.json") != receipt["selected_sha256"]:
        raise ValueError("Selected recipe changed")
    if sha(root / "development_complete.json") != receipt["development_barrier_sha256"]:
        raise ValueError("Selection development barrier changed")


def verify_forecast(root):
    verify_selection(root)
    receipt = read(root / "forecast_complete.json")
    if sha(root / "frozen_forecasts.json") != receipt["forecast_sha256"]:
        raise ValueError("Forecast changed")
    if sha(root / "bridge_complete.json") != receipt["bridge_barrier_sha256"]:
        raise ValueError("Forecast bridge barrier changed")
    if (
        sha(root / "selected_recipes.json")
        != read(root / "frozen_forecasts.json")["selected_sha256"]
    ):
        raise ValueError("Forecast recipe binding changed")


def observation_seed(config, teacher, observation):
    return config["observation_seed_base"] + 100 * teacher + 2 * observation


def dataset_path(root, stage, task, teacher, observation):
    release = "confirmation" if stage == "confirmation" else "development"
    return root / "data" / release / f"{task}_t{teacher}_o{observation}.npz"


def create_datasets(root, config, release):
    if release == "confirmation":
        verify_forecast(root)
    indices = config[f"{release}_teachers"]
    endpoint = "test" if release == "confirmation" else "validation"
    for teacher_index in indices:
        for response in ("mixture", "quadratic"):
            teacher = tasks.make_teacher(
                tasks.TaskConfig(
                    response, teacher_index, config["teacher_seed_base"] + teacher_index
                )
            )
            private_path = (
                root
                / "private_teachers"
                / f"{release}_{response}_t{teacher_index}.json"
            )
            specification = teacher.specification()
            if private_path.exists():
                if read(private_path) != specification:
                    raise ValueError("Existing teacher specification differs")
            else:
                write(private_path, specification)
            for observation in range(2 if release == "confirmation" else 1):
                for q in (1, 2) if response == "mixture" else (2,):
                    task = f"{response}_q{q}"
                    path = dataset_path(root, release, task, teacher_index, observation)
                    if path.exists() and path.with_suffix(".json").exists():
                        if sha(path) != read(path.with_suffix(".json"))["sha256"]:
                            raise ValueError("Existing data changed")
                        continue
                    seed = observation_seed(config, teacher_index, observation)
                    generated = tasks.generate_data(
                        teacher,
                        seed,
                        q,
                        config["main_n"],
                        endpoint,
                        config[endpoint + "_n"],
                    )
                    arrays = {
                        "x_train": generated["train_x"],
                        "y_train": generated["train_y_clean"],
                        "x_endpoint": generated[endpoint + "_x"],
                        "y_endpoint": generated[endpoint + "_y_clean"],
                    }
                    path.parent.mkdir(parents=True, exist_ok=True)
                    with path.open("xb") as stream:
                        np.savez_compressed(stream, **arrays)
                    write(
                        path.with_suffix(".json"),
                        {
                            "utc": now(),
                            "release": release,
                            "endpoint": endpoint,
                            "task": task,
                            "teacher": teacher_index,
                            "observation": observation,
                            "seed": seed,
                            "sha256": sha(path),
                            "private_specification_sha256": sha(private_path),
                            "forecast_sha256": (
                                sha(root / "frozen_forecasts.json")
                                if release == "confirmation"
                                else None
                            ),
                        },
                    )


def initialize(root, config):
    if (root / "initialized.json").exists():
        verify(root)
        if read(root / "config.json") != config:
            raise ValueError("Existing configuration differs")
    else:
        if (
            not (root / "protocol.md").is_file()
            or not (root / "timing_decision.json").is_file()
        ):
            raise ValueError(
                "Protocol and timing-only teacher-count decision must precede initialization"
            )
        timing = read(root / "timing_decision.json")
        if timing["confirmation_teacher_count"] != len(config["confirmation_teachers"]):
            raise ValueError("Teacher count differs from timing-only decision")
        write(root / "config.json", config)
        write(root / "choices.json", choices(config))
        write(
            root / "parameter_inventory.json",
            width.matched_ceiling_inventory(config["primary_p"]),
        )
        paths = [
            root / name
            for name in (
                "config.json",
                "choices.json",
                "protocol.md",
                "timing_decision.json",
                "parameter_inventory.json",
            )
        ]
        paths += sorted((root / "source").glob("*.py"))
        if Path(__file__).resolve() not in [p.resolve() for p in paths]:
            raise ValueError("Run the source snapshot inside the study root")
        write(
            root / "initialized.json",
            {
                "utc": now(),
                "bindings": {str(p.relative_to(root)): sha(p) for p in paths},
            },
        )
    create_datasets(root, config, "development")


def case_key(case):
    return "/".join(
        str(case[key])
        for key in (
            "stage",
            "task",
            "geometry",
            "family",
            "teacher",
            "observation",
            "choice",
            "coverage",
            "rebalance",
            "ceiling",
        )
    )


def case_grid(config, stage, recipes=None):
    result = []
    indices = (
        config["confirmation_teachers"]
        if stage == "confirmation"
        else config["development_teachers"]
    )
    for task, geometry, family, teacher, observation in itertools.product(
        config["tasks"],
        config["geometries"],
        config["families"],
        indices,
        range(2 if stage == "confirmation" else 1),
    ):
        common = {
            "stage": stage,
            "task": task,
            "geometry": geometry,
            "family": family,
            "teacher": teacher,
            "observation": observation,
        }
        if stage == "diagnostic":
            if (
                task not in ("mixture_q2", "quadratic_q2")
                or family not in ("shunt", "relu")
                or geometry not in ("rank2", "full", "width2")
            ):
                continue
            starts = (
                [("ols", "legacy"), ("ols", "axial"), ("stein", "axial")]
                if geometry == "rank2"
                else [("ols", "axial"), ("stein", "axial")]
            )
            for (method, coverage), rebalance in itertools.product(
                starts, [False, True] if geometry == "rank2" else [True]
            ):
                result.append(
                    dict(
                        common,
                        choice=f"{method}_ridge1e-05",
                        coverage=coverage,
                        rebalance=rebalance,
                        ceiling=config["bridge_p"],
                    )
                )
        else:
            selected = (
                [c["id"] for c in choices(config)]
                if stage == "development"
                else [recipes[f"{task}/{geometry}/{family}"]["choice"]]
            )
            budgets = (
                config["calibration_p"]
                if stage == "development"
                else (
                    [config["bridge_p"]] if stage == "bridge" else config["primary_p"]
                )
            )
            for choice, ceiling in itertools.product(selected, budgets):
                result.append(
                    dict(
                        common,
                        choice=choice,
                        coverage="axial",
                        rebalance=True,
                        ceiling=ceiling,
                    )
                )
    if len(result) != config["fit_counts"][stage]:
        raise ValueError(f"Case count mismatch: {stage}, {len(result)}")
    if len({case_key(c) for c in result}) != len(result):
        raise ValueError("Duplicate case keys")
    return sorted(result, key=lambda c: (-c["ceiling"], case_key(c)))


@lru_cache(maxsize=64)
def load_train(path_string):
    path = Path(path_string)
    if sha(path) != read(path.with_suffix(".json"))["sha256"]:
        raise ValueError("Dataset hash differs")
    with np.load(path, allow_pickle=False) as archive:
        return archive["x_train"].copy(), archive["y_train"].copy()


def verify_result(root, receipt, case):
    if receipt["case"] != case or receipt["initialized_sha256"] != sha(
        root / "initialized.json"
    ):
        raise ValueError("Completed case/source binding mismatch")
    for stem in ("data", "fit", "state", "predictions"):
        if stem != "data" and receipt["status"] != "complete":
            continue
        if sha(receipt[stem + "_path"]) != receipt[stem + "_sha256"]:
            raise ValueError(f"Completed {stem} artifact changed")
    expected_data = dataset_path(
        root, case["stage"], case["task"], case["teacher"], case["observation"]
    )
    if Path(receipt["data_path"]).resolve() != expected_data.resolve():
        raise ValueError("Case data path differs from its declared split")


def run_case(root_string, case):
    root = Path(root_string)
    torch.set_num_threads(1)
    verify(root)
    config = read(root / "config.json")
    if case["stage"] == "confirmation":
        verify_forecast(root)
    elif case["stage"] == "bridge":
        verify_selection(root)
    recipes = (
        read(root / "selected_recipes.json")
        if case["stage"] in ("bridge", "confirmation")
        else None
    )
    if case not in case_grid(config, case["stage"], recipes):
        raise ValueError("Worker case outside frozen grid")
    case_dir = root / "cases" / case_key(case)
    result_path = case_dir / "result.json"
    if result_path.exists():
        receipt = read(result_path)
        verify_result(root, receipt, case)
        return receipt
    case_dir.mkdir(parents=True, exist_ok=True)
    # A preempted attempt remains intact. Resume starts a separately numbered
    # attempt, with identical data, seed and recipe; completed failures do not retry.
    attempt_number = len(list(case_dir.glob("attempt_*")))
    attempt = case_dir / f"attempt_{attempt_number:03d}"
    attempt.mkdir(exist_ok=False)
    write(attempt / "case.json", case)
    started = time.monotonic()
    data_path = dataset_path(
        root, case["stage"], case["task"], case["teacher"], case["observation"]
    )
    receipt = {
        "case": case,
        "utc": now(),
        "data_path": str(data_path),
        "data_sha256": sha(data_path),
        "attempt_path": str(attempt),
        "previous_incomplete_attempts": attempt_number,
        "initialized_sha256": sha(root / "initialized.json"),
    }
    try:
        x, y = load_train(str(data_path))
        choice = next(
            c for c in read(root / "choices.json") if c["id"] == case["choice"]
        )
        bank, init_receipt = initializer.estimate_subspaces(
            x, y, method=choice["method"]
        )
        seed = (
            config["model_seed_base"] + 100 * case["teacher"] + 2 * case["observation"]
        )
        model = width.model_under_ceiling(
            case["ceiling"],
            case["family"],
            case["geometry"],
            allocation_seed=case["teacher"],
            train_data=(x, y),
            bank=bank,
            initialization_module=initializer,
            coverage=case["coverage"],
            initializer_receipt=init_receipt,
            seed=seed,
            base_module=base,
        )
        write(attempt / "initializer.json", init_receipt)
        fit = optimizer.fit_restarted(
            model.model,
            model.expanded_inputs(x),
            y,
            base.FitConfig(**choice["fit"]),
            stages=config["stages"],
            rebalance=case["rebalance"],
            output_dir=attempt / "fit",
        )
        # Held-out arrays are first materialized after the optimizer terminates.
        with np.load(data_path, allow_pickle=False) as archive:
            endpoint_x, endpoint_y = (
                archive["x_endpoint"].copy(),
                archive["y_endpoint"].copy(),
            )
        with torch.no_grad():
            train_prediction = model(x).cpu().numpy()
            endpoint_prediction = model(endpoint_x).cpu().numpy()
        if (
            not np.isfinite(train_prediction).all()
            or not np.isfinite(endpoint_prediction).all()
        ):
            raise FloatingPointError("Nonfinite endpoint")
        with (attempt / "predictions.npz").open("xb") as stream:
            np.savez_compressed(
                stream, train=train_prediction, endpoint=endpoint_prediction
            )
        metrics = {
            "train_mse": float(np.mean((train_prediction - y) ** 2)),
            "endpoint_mse": float(np.mean((endpoint_prediction - endpoint_y) ** 2)),
        }
        receipt.update(
            status="complete",
            metrics=metrics,
            ridge=choice["fit"]["ridge"],
            fit_path=str(attempt / "fit/fit.json"),
            fit_sha256=sha(attempt / "fit/fit.json"),
            state_path=str(attempt / "fit/final.npz"),
            state_sha256=sha(attempt / "fit/final.npz"),
            predictions_path=str(attempt / "predictions.npz"),
            predictions_sha256=sha(attempt / "predictions.npz"),
            counted_inventory=model.counted_metadata(),
            objective=fit["terminal_objective"],
            closure_calls=fit["closure_calls"],
            iterations=fit["iterations"],
            fit_elapsed_seconds=fit["elapsed_seconds"],
        )
    except Exception:
        receipt.update(status="failed", traceback=traceback.format_exc())
    receipt["elapsed_seconds"] = time.monotonic() - started
    write(result_path, receipt)
    return receipt


def stage_results(root, stage, config):
    recipes = (
        read(root / "selected_recipes.json")
        if stage in ("bridge", "confirmation")
        else None
    )
    cases = case_grid(config, stage, recipes)
    paths = [root / "cases" / case_key(case) / "result.json" for case in cases]
    marker = root / f"{stage}_complete.json"
    if marker.exists():
        recorded = read(marker)
        if recorded["fits"] != len(cases) or recorded["results"] != {
            str(path.relative_to(root)): sha(path) for path in paths
        }:
            raise ValueError("Stage result bytes differ from completion barrier")
    rows = [read(path) for path in paths]
    if any(
        row["status"] != "complete" or row["case"] != case
        for row, case in zip(rows, cases)
    ):
        raise ValueError(
            "Complete, correctly bound outcomes required; failures cannot be dropped"
        )
    for row, case in zip(rows, cases):
        verify_result(root, row, case)
    return rows


def execute_stage(root, stage, workers):
    verify(root)
    config = read(root / "config.json")
    if stage == "confirmation":
        verify_forecast(root)
    elif stage == "bridge":
        verify_selection(root)
    if stage in ("bridge", "confirmation"):
        stage_results(root, "development", config)
    if stage == "confirmation":
        stage_results(root, "bridge", config)
        create_datasets(root, config, "confirmation")
    cases = case_grid(
        config,
        stage,
        (
            read(root / "selected_recipes.json")
            if stage in ("bridge", "confirmation")
            else None
        ),
    )
    marker = root / f"{stage}_complete.json"
    if marker.exists():
        stage_results(root, stage, config)
        return
    started = time.monotonic()
    with ProcessPoolExecutor(
        max_workers=workers, mp_context=multiprocessing.get_context("spawn")
    ) as pool:
        futures = [pool.submit(run_case, str(root), case) for case in cases]
        for index, future in enumerate(as_completed(futures)):
            row = future.result()
            print(
                json.dumps(
                    {
                        "stage": stage,
                        "done": index + 1,
                        "total": len(cases),
                        "case": case_key(row["case"]),
                        "status": row["status"],
                    }
                ),
                flush=True,
            )
    rows = stage_results(root, stage, config)
    write(
        marker,
        {
            "utc": now(),
            "status": "complete",
            "fits": len(rows),
            "workers": workers,
            "elapsed_seconds": time.monotonic() - started,
            "results": {
                str(
                    (
                        root / "cases" / case_key(row["case"]) / "result.json"
                    ).relative_to(root)
                ): sha(root / "cases" / case_key(row["case"]) / "result.json")
                for row in rows
            },
        },
    )


def select(root):
    verify(root)
    if (root / "selection_complete.json").exists():
        verify_selection(root)
        return
    config = read(root / "config.json")
    rows = stage_results(root, "development", config)
    recipes = {}
    for task, geometry, family in itertools.product(
        config["tasks"], config["geometries"], config["families"]
    ):
        subset = [
            r
            for r in rows
            if all(
                r["case"][k] == v
                for k, v in zip(
                    ("task", "geometry", "family"), (task, geometry, family)
                )
            )
        ]
        scores = {}
        for choice in choices(config):
            selected = [r for r in subset if r["case"]["choice"] == choice["id"]]
            if len(selected) != len(config["development_teachers"]) * len(
                config["calibration_p"]
            ):
                raise ValueError("Unbalanced development outcomes")
            scores[choice["id"]] = float(
                np.mean(
                    np.log(
                        [
                            max(
                                config["log_risk_threshold"],
                                r["metrics"]["endpoint_mse"],
                            )
                            for r in selected
                        ]
                    )
                )
            )
        recipes[f"{task}/{geometry}/{family}"] = {
            "choice": min(scores, key=lambda key: (scores[key], key)),
            "mean_log_validation_scores": scores,
        }
    write(root / "selected_recipes.json", recipes)
    write(
        root / "selection_complete.json",
        {
            "utc": now(),
            "selected_sha256": sha(root / "selected_recipes.json"),
            "development_barrier_sha256": sha(root / "development_complete.json"),
            "rule": "Minimum mean log validation MSE across two development teachers and two calibration budgets; lexical choice ID breaks exact ties. Four equal tuning choices per arm. Diagnostic outcomes never enter selection.",
        },
    )


def forecasts_from_rows(config, recipes, rows):
    curves = {}
    for key, selected in recipes.items():
        task, geometry, family = key.split("/")
        subset = [
            r
            for r in rows
            if (
                r["case"]["task"],
                r["case"]["geometry"],
                r["case"]["family"],
                r["case"]["choice"],
            )
            == (task, geometry, family, selected["choice"])
            and r["case"]["coverage"] == "axial"
            and r["case"]["rebalance"]
        ]
        ps, log_risks = [], []
        for ceiling in sorted(config["calibration_p"] + [config["bridge_p"]]):
            values = [r for r in subset if r["case"]["ceiling"] == ceiling]
            if len(values) != len(config["development_teachers"]):
                raise ValueError(
                    "Forecast needs every selected development teacher at every disclosed size"
                )
            ps.append(values[0]["counted_inventory"]["stored_parameters"])
            log_risks.append(
                float(
                    np.mean(
                        [
                            np.log(
                                max(
                                    config["log_risk_threshold"],
                                    r["metrics"]["endpoint_mse"],
                                )
                            )
                            for r in values
                        ]
                    )
                )
            )
        pnew = width.parameter_inventory(
            width.branches_under_ceiling(config["withheld_p"], geometry), geometry
        )["stored_parameters"]
        power = np.polyfit(np.log(ps), log_risks, 1)
        exponential = np.polyfit(ps, log_risks, 1)
        curves[key] = {
            "actual_parameters": ps,
            "mean_log_validation_risks": log_risks,
            "withheld_actual_parameters": pnew,
            "constant_log_risk": log_risks[-1],
            "power_log_risk": float(np.polyval(power, np.log(pnew))),
            "exponential_log_risk": float(np.polyval(exponential, pnew)),
            "power_slope": float(power[0]),
            "exponential_slope": float(exponential[0]),
        }
    comparisons = []
    for task, family, (numerator, denominator) in itertools.product(
        config["tasks"],
        config["families"],
        [
            ("width1", "full"),
            ("width2", "full"),
            ("rank2", "full"),
            ("width2", "rank2"),
        ],
    ):
        delta = (
            curves[f"{task}/{numerator}/{family}"]["mean_log_validation_risks"][-1]
            - curves[f"{task}/{denominator}/{family}"]["mean_log_validation_risks"][-1]
        )
        comparisons.append(
            {
                "task": task,
                "family": family,
                "numerator": numerator,
                "denominator": denominator,
                "development_log_ratio": delta,
                "predicted_numerator_better": delta < 0,
            }
        )
    return {"curves": curves, "architecture_predictions": comparisons}


def freeze(root):
    verify_selection(root)
    if (root / "forecast_complete.json").exists():
        verify_forecast(root)
        return
    if (root / "data/confirmation").exists():
        raise ValueError("Fresh confirmation data must not precede forecast freeze")
    config = read(root / "config.json")
    rows = stage_results(root, "development", config) + stage_results(
        root, "bridge", config
    )
    forecasts = forecasts_from_rows(config, read(root / "selected_recipes.json"), rows)
    write(
        root / "frozen_forecasts.json",
        {
            "utc": now(),
            "selected_sha256": sha(root / "selected_recipes.json"),
            **forecasts,
            "scope": "Three disclosed development sizes. Constant-last, log-log power, and log-risk-linear-in-P forecasts all evaluated; no model chosen on test. Architecture directions extrapolate selected P965 validation comparisons to P1925. Forecast slopes are finite-range predictions, not established exponents.",
        },
    )
    write(
        root / "forecast_complete.json",
        {
            "utc": now(),
            "forecast_sha256": sha(root / "frozen_forecasts.json"),
            "bridge_barrier_sha256": sha(root / "bridge_complete.json"),
        },
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument(
        "--stage",
        choices=[
            "initialize",
            "diagnostic",
            "development",
            "select",
            "bridge",
            "freeze",
            "confirmation",
            "complete",
            "all",
        ],
        required=True,
    )
    parser.add_argument("--teachers", type=int, choices=[4, 8], default=4)
    parser.add_argument("--workers", type=int, default=16)
    args = parser.parse_args()
    root = args.root.resolve()
    torch.set_num_threads(1)
    stages = (
        [
            "initialize",
            "diagnostic",
            "development",
            "select",
            "bridge",
            "freeze",
            "confirmation",
            "complete",
        ]
        if args.stage == "all"
        else [args.stage]
    )
    for stage in stages:
        if stage == "initialize":
            initialize(root, configuration(args.teachers))
        elif stage in ("diagnostic", "development", "bridge", "confirmation"):
            execute_stage(root, stage, args.workers)
        elif stage == "select":
            select(root)
        elif stage == "freeze":
            freeze(root)
        else:
            verify_forecast(root)
            config = read(root / "config.json")
            rows = [
                row
                for s in config["fit_counts"]
                for row in stage_results(root, s, config)
            ]
            if len(rows) != config["expected_fits"]:
                raise ValueError("Final total differs from frozen count")
            write(
                root / "complete.json",
                {
                    "utc": now(),
                    "status": "complete",
                    "fits": len(rows),
                    "fit_counts": config["fit_counts"],
                    "summed_fit_seconds": sum(r["fit_elapsed_seconds"] for r in rows),
                    "scope": "Fitting complete; independent numerical audit and interpretation are separate.",
                },
            )


if __name__ == "__main__":
    main()
