"""Public facade for transformer dendritic replacement training."""

from __future__ import annotations

from dendritic_modeling.training._transformer_replacement.builders import (
    _make_replacement,
    _make_single_layer_ei_stack_replacement,
    _make_synthetic_units,
    _records_to_units,
    _replacement_kind,
)
from dendritic_modeling.training._transformer_replacement.checkpoints import (
    _copy_replacement_state_dict,
    _load_replacement_record_checkpoints,
    _load_replacement_state_dict,
    _remap_single_layer_stack_state_dict,
)
from dendritic_modeling.training._transformer_replacement.common import (
    DistillationUnit,
    SyntheticTransformerMLP,
    TransformerReplacementBenchmarkResult,
    TransformerReplacementTrainingResult,
    _activation,
    _compute_distillation_loss,
    _replacement_forward_modules,
    _resolve_device,
    _resolve_dtype,
    _to_plain_mapping,
)
from dendritic_modeling.training._transformer_replacement.data import (
    _build_hidden_cache_units_and_datasets,
    _build_synthetic_datasets,
    _extract_mlp_output,
    _load_hf_causal_lm_for_joint_training,
    _load_hf_teacher_and_units,
    _load_tensor,
    _MLPIOCapture,
    _read_token_source,
    _sample_hidden_pairs,
    _sample_token_batch,
    _select_layer_tensor,
    read_transformer_token_source,
    sample_transformer_token_batch,
)
from dendritic_modeling.training._transformer_replacement.evaluation import (
    _benchmark_hf_text_replacement,
    _compute_prediction_metrics,
    _evaluate_lm_loss_on_tokens,
    _evaluate_tensor_dataset_metrics,
    _evaluate_tensor_datasets,
    _synthetic_teacher_parameter_count,
    benchmark_saved_transformer_replacement,
)
from dendritic_modeling.training._transformer_replacement.joint import (
    _freeze_except_replacements,
    _joint_lm_distillation_loss,
    _resolve_joint_hidden_layers,
    _select_joint_trainable_parameters,
)
from dendritic_modeling.training._transformer_replacement.loops import (
    _evaluate_hf_text,
    _save_result,
    _train_hf_text_source,
    _train_joint_hf_text_source,
    _train_tensor_dataset_source,
    run_transformer_replacement_training,
)
from dendritic_modeling.training._transformer_replacement.token_stream import (
    FrozenWindowBatchSource,
    StreamingTokenBatchSource,
)

__all__ = [
    "DistillationUnit",
    "FrozenWindowBatchSource",
    "StreamingTokenBatchSource",
    "SyntheticTransformerMLP",
    "TransformerReplacementBenchmarkResult",
    "TransformerReplacementTrainingResult",
    "_MLPIOCapture",
    "_activation",
    "_benchmark_hf_text_replacement",
    "_build_hidden_cache_units_and_datasets",
    "_build_synthetic_datasets",
    "_compute_distillation_loss",
    "_compute_prediction_metrics",
    "_copy_replacement_state_dict",
    "_evaluate_hf_text",
    "_evaluate_lm_loss_on_tokens",
    "_evaluate_tensor_dataset_metrics",
    "_evaluate_tensor_datasets",
    "_extract_mlp_output",
    "_freeze_except_replacements",
    "_joint_lm_distillation_loss",
    "_load_hf_causal_lm_for_joint_training",
    "_load_hf_teacher_and_units",
    "_load_replacement_record_checkpoints",
    "_load_replacement_state_dict",
    "_load_tensor",
    "_make_replacement",
    "_make_single_layer_ei_stack_replacement",
    "_make_synthetic_units",
    "_read_token_source",
    "_records_to_units",
    "_remap_single_layer_stack_state_dict",
    "_replacement_forward_modules",
    "_replacement_kind",
    "_resolve_device",
    "_resolve_dtype",
    "_resolve_joint_hidden_layers",
    "_sample_hidden_pairs",
    "_sample_token_batch",
    "_save_result",
    "_select_joint_trainable_parameters",
    "_select_layer_tensor",
    "_synthetic_teacher_parameter_count",
    "_to_plain_mapping",
    "_train_hf_text_source",
    "_train_joint_hf_text_source",
    "_train_tensor_dataset_source",
    "benchmark_saved_transformer_replacement",
    "read_transformer_token_source",
    "run_transformer_replacement_training",
    "sample_transformer_token_batch",
]
