#!/usr/bin/env python3
"""Verified aggregation; no outcome filtering or significance-based selection."""
import argparse,json
from pathlib import Path
import numpy as np
import pandas as pd
from run import OUT,sha,write

def interval(values):
 x=np.asarray(values,float);rng=np.random.default_rng(982211);boot=x[rng.integers(len(x),size=(20000,len(x)))].mean(1);return float(x.mean()),*np.quantile(boot,[.025,.975]).tolist()

def report(root):
 root=Path(root);cfg=json.loads((root/'protocol.json').read_text());selection=json.loads((root/'selection_freeze.json').read_text());target=selection['selected_task'];control=cfg['task_selection']['control'];out=root/'summaries';out.mkdir(exist_ok=True);allends=[];allcurves=[];alldiag=[];allmeta=[];inventory=[];counts={}
 for phase in ['development','fresh','extension']:
  folder=root/'extension' if phase=='extension' else root/'runs'/phase;seeds=cfg['development_seeds'] if phase=='development' else cfg['fresh_seeds'];frames={k:[] for k in ['endpoints','curves','diagnostics']}
  for seed in seeds:
   p=folder/f'seed_{seed}_audit.json';audit=json.loads(p.read_text());inventory.append(dict(path=str(p.relative_to(root)),sha256=sha(p)))
   for f,digest in audit['files_sha256'].items():
    pp=folder/f;assert sha(pp)==digest;inventory.append(dict(path=str(pp.relative_to(root)),sha256=digest))
    if f.endswith('_metadata.json'): allmeta.append(json.loads(pp.read_text()))
   for kind in frames: frames[kind].append(pd.read_csv(folder/f'seed_{seed}_{kind}.csv'))
  joined={k:pd.concat(v,ignore_index=True) for k,v in frames.items()};counts[phase]=len(joined['endpoints']);allends.append(joined['endpoints']);allcurves.append(joined['curves']);alldiag.append(joined['diagnostics'])
 ends=pd.concat(allends,ignore_index=True);curves=pd.concat(allcurves,ignore_index=True);diag=pd.concat(alldiag,ignore_index=True);ends.to_csv(out/'all_endpoints.csv',index=False);curves.to_csv(out/'all_curves.csv',index=False);diag.to_csv(out/'all_diagnostics.csv',index=False);pd.DataFrame(inventory).drop_duplicates().to_csv(out/'outcome_inventory.tsv',sep='\t',index=False)
 contrasts=[];paired=[]
 for phase in ['fresh','extension']:
  for opt in cfg['rates']:
   for scope,flag in [('selected','selected_rate'),('common','common_rate')]:
    part=ends[(ends.phase==phase)&(ends.optimizer==opt)&ends[flag]]
    for rule in [r for r in cfg['rules'] if r!='exact']:
     wide=part.pivot(index='seed',columns=['task','rule'],values='test_nmse');tg=wide[(target,rule)]-wide[(target,'exact')];cg=wide[(control,rule)]-wide[(control,'exact')]
     for name,values in [('target_gap',tg),('control_gap',cg),('task_difference_in_gap',tg-cg)]:
      mean,lo,hi=interval(values);contrasts.append(dict(phase=phase,optimizer=opt,rate_scope=scope,rule=rule,contrast=name,n=len(values),mean=mean,ci_low=lo,ci_high=hi,n_positive=int((values>0).sum()),n_negative=int((values<0).sum())))
      for seed,value in values.items():paired.append(dict(seed=seed,phase=phase,optimizer=opt,rate_scope=scope,rule=rule,contrast=name,value=value))
 pd.DataFrame(contrasts).to_csv(out/'paired_contrasts.csv',index=False);pd.DataFrame(paired).to_csv(out/'paired_seed_contrasts.csv',index=False)
 means=ends[ends.selected_rate].groupby(['phase','task','optimizer','rule'],as_index=False).mean(numeric_only=True);means.to_csv(out/'selected_rate_means.csv',index=False)
 teacher=[]
 for m in allmeta:
  teacher.append(dict(seed=m['seed'],phase=m['phase'],task=m['task']['name'],target_variance=m['test_target_variance'],constructive_forward_nmse=m['constructive_forward_nmse'],**m['teacher_geometry']))
 pd.DataFrame(teacher).to_csv(out/'teacher_geometry.csv',index=False)
 primary=pd.DataFrame(contrasts);primary=primary[(primary.phase=='extension')&(primary.optimizer=='adam')&(primary.rate_scope=='selected')&(primary.rule=='calibrated_broadcast')]
 lines=['# Conductance credit comparison: complete outcomes','',f'Counts: {counts}. The extension continues every fresh condition; it does not add independent seed blocks.','',f'Selected target: `{target}`; paired control: `{control}`.','', '## Selected-rate test NMSE','',means[['phase','task','optimizer','rule','test_nmse']].to_markdown(index=False),'','## Extended-budget Adam calibrated-profile contrasts','',primary.to_markdown(index=False),'','All source audits and outcome SHA256 identities passed. Complete development rates, initial and saved-checkpoint geometry, curves and paired seed values are provided beside this report. Geometry is a descriptive oracle projection, not a learned routing encoder or a theorem of learning necessity. At fixed weights the path field depends only on binary context and therefore has rank at most two.','', 'All local and coupling conductances are trainable. The target is generated by the same forward model and its constructive clean NMSE floor is exactly zero. Noise is zero. All comparisons use the same seed-specific initial parameters, input samples, contexts and minibatches within the stated task pairing. Positive path factors make the fixed-profile update acute with each individual-example exact gradient; conflicting averages and optimizer dynamics are the tested issue.','', 'Learning uses fixed budgets, validation-selected saved states, and an unchanged-state extension from4096 to16384 updates. The endpoint is not declared converged. The recorded clipping counts matter for interpreting positive fixed profiles under Adam: global clipping can break the exact invariance to constant per-coordinate scaling.','']
 if root.name=='opponent':
  lines += ['## Secondary boundary and conductance-range checks','', 'The moderate-gating development regime has teacher rank-one path capture near0.98 but a large broadcast deficit. Raw path-energy capture is not a sufficient criterion for learning; its small remaining spatial component can carry the distinction between competing context gradients. Strong and aligned teacher fields also have similar raw geometry despite different task demands. The context-gradient audit and three-pattern rescue, not a scalar rank threshold, supply the mechanistic evidence.','']
  bound_path=root/'bound_sensitivity/summaries/paired_contrasts.csv'
  if bound_path.exists():
   b=pd.read_csv(bound_path);b=b[(b.rule=='calibrated_broadcast')&(b.contrast=='task_difference_in_gap')];lines += [b.to_markdown(index=False),'','All320 original-bound trajectories replay exactly. The paired gap is already positive in every Adam seed at its last saved checkpoint before the first original bound contact. Some broadcast parameters reach even the wider bounds; these remain finite-budget comparisons, not a claim of unbounded convergence.','']
 (root/'RESULTS.md').write_text('\n'.join(lines));write(out/'audit.json',dict(outcome_counts=counts,n_verified_outcome_files=len(pd.DataFrame(inventory).drop_duplicates()),all_outcome_hashes_pass=True,all_development_candidates_retained=True,primary_selection_frozen_before_fresh=True,report_source_sha256=sha(Path(__file__))))
 print(json.dumps(counts));print(primary.to_string(index=False))

if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--root',type=Path,default=OUT);a=p.parse_args();report(a.root)
