#!/usr/bin/env python3
"""Main Fig. 5: a local inhibitory gate in a seven-compartment conductance tree.

Redraws only figures from the existing complete summaries; no training, no
summary edits.  The frozen protocol and every numerical summary are verified
byte-for-byte before anything is read (``portable_contract.verify``), the
Supplementary all-rates figure is regenerated by ``report.figures`` exactly
as before, and the main figure is then rebuilt on the ``NativeCanvas``
(DESIGN_SPEC section 5) at the same output path.

Grid: ``NativeCanvas(490/72, 3, row_weights=[134, 108, 108], hgutter 38,
vgutter 43, margins 54/14/22/32)`` (left 54: the 37-pt y-label stacks of
C and E must clear the 16.8-pt letter column; hgutter 38: F's y-label
stack plus its letter must clear E's axes corner); 22 + 134 + 43 + 108 + 43 + 108 + 32 =
490 pt (spec range 484-492, aspect 1.06).  The spec's 34-pt vgutter with
136/112/112 rows left 5.5 pt of ink between the C/D x labels and the E-G
letter band, under the 8.5-pt (3 mm) floor of ``audit_row_separation``;
the gutter must hold that 23-pt tick + x-label stack and the 13-pt letter
band plus the floor, so it grows to 43 pt and the rows give the height back.
Row 0: A (5 modules, task schematic with the nominal-teacher inset) + B (7,
the four deliveries as 2 x 2 cards); row 1: C (6) + D (6) sharing the
log-NMSE axis; row 2: E, F, G (4/4/4).

Waiver (spec D3): E, F and G are three 4-module panels of one comparison
family -- E keeps the log-NMSE range of C/D, F and G share the 0-1 tick set.

Every schematic element is drawn with the shared glyph library
(``native_schematics.Frame``).  Private helpers (errata #7) cover what the
library does not draw: the D5 amber bus sourced at the soma (the library's
'scalar' mode has no soma source and its 'neuron' mode draws the retired
barrier glyph), an open (gated-to-zero) arrowhead, token-subscript chains
for key lines, a plain '1e-6'-style log formatter (no ``plain_log_formatter``
exists in ``figure_canvas``) and a badge next to a legend entry.  Every
printed number is derived here from the Source Data named in
``figure_provenance.json``; the nominal teacher tuning is computed by
``model.forward`` from ``model.teacher``'s own gains with the perturbation
set to zero and written to ``figures/teacher_tuning_source.csv``.
"""
import hashlib
import json
import sys
from pathlib import Path
from unittest import mock

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrowPatch
from matplotlib.ticker import FixedLocator, NullFormatter, NullLocator

from report import OUT, figures, boot
from portable_contract import J, load_protocol, verify
import model

sys.path.insert(0, str(J / 'scripts'))
from figure_canvas import (COLORS, LW_DATA, LW_EDGE, LW_ERR, LW_HAIR, LW_REF,  # noqa: E402
                           MARKER_MS, PT_ANNOT, PT_LABEL, PT_LEGEND, PT_SMALL,
                           PT_TICK, SEED_ALPHA, SEED_MS, Margins, NativeCanvas,
                           audit_native_pdf, style_panel, token_subscript)
from journal_style import label_color  # noqa: E402
from credit_tree_schematics import AMBER_TEXT, mix  # noqa: E402
from native_schematics import (BADGE_STYLE, CONTACT_DIA_PT, Frame, _lerp,  # noqa: E402
                               _text_w_pt, reference_line)

FIG = OUT / 'figures'
PDF = FIG / 'local_gate_primary.pdf'
INK, MUTE = COLORS['ink'], COLORS['mute']
DASH = (0, (2.2, 1.8))
RULES = {  # rule key -> (legend / category label, colour key)
    'exact': ('Exact path', 'bp'),
    'hard_distal_unit_proximal': ('Local distal gate', 'shunting'),
    'unit_broadcast': ('Unit broadcast', 'scalar'),
    'ancestry_two_leaf_oracle_unit_proximal': ('Two-leaf oracle', 'oracle'),
    'swapped_distal_unit_proximal': ('Swapped gate', 'point_mlp'),
    'hard_distal_and_proximal': ('Gate also proximal', 'highlight'),
    'calibrated_broadcast': ('Calibrated broadcast', 'per_soma'),
}
CURVE_RULES = ('exact', 'hard_distal_unit_proximal', 'unit_broadcast',
               'ancestry_two_leaf_oracle_unit_proximal')
SUBTREE = (('JL', 'dend'), ('JR', 'soma'))      # K_CYCLE tints (spec D7)
PRIMARY = dict(rate=0.03, budget=4096)
LOG_TICKS = (1e-6, 1e-4, 1e-2, 1)
LOG_YLIM = (1e-6, 2.0)
UNIT_YLIM = (-0.22, 1.46)               # F and G share the 0-1 tick set
HIST_SEED = 982211                      # descriptive bootstrap RNG, as report.py
ROWS_PT = [134, 108, 108]
VGUTTER_PT = 43
HGUTTER_PT = 38
MARGINS = dict(left=54, right=14, top=22, bottom=32)
HEIGHT_PT = MARGINS['top'] + sum(ROWS_PT) + 2 * VGUTTER_PT + MARGINS['bottom']   # 490


def rc(key):
    return COLORS[RULES[key][1]]


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def true_minus(s):
    return str(s).replace('-', '−')


def sci(v):
    """'2e−5'-style mantissa/exponent string with a true minus, no mathtext."""
    m, e = f'{v:.0e}'.split('e')
    return f'{m}e{true_minus(int(e))}'


# ── private glyph helpers (library geometry, spec 0.2; errata #7) ─────────
def chain(f, xy, parts, *, size=PT_SMALL, color=None, ha='left', va='center',
          zorder=6):
    """Plain strings and (base, sub) pairs laid out left-to-right at ``xy``.

    ``Frame.subscript`` draws every pair (token subscripts, never mathtext)
    and each piece is measured so the run can be centred or right-anchored.
    """
    color = INK if color is None else color
    base_size = PT_ANNOT if size <= PT_SMALL else size
    widths = []
    for p in parts:
        if isinstance(p, tuple):
            widths.append(_text_w_pt(f.ax, p[0], base_size) + 0.4
                          + _text_w_pt(f.ax, p[1], PT_SMALL))
        else:
            widths.append(_text_w_pt(f.ax, p, size))
    total = sum(widths)
    x, y = xy
    if ha == 'center':
        x -= f.fx(total / 2.0)
    elif ha == 'right':
        x -= f.fx(total)
    for p, w in zip(parts, widths):
        if isinstance(p, tuple):
            f.subscript((x, y), p[0], p[1], size=size, color=color, ha='left',
                        va=va, zorder=zorder)
        else:
            f.text((x, y), p, size=size, color=color, ha='left', va=va,
                   zorder=zorder)
        x += f.fx(w)
    return total


def amber_bus(f, nodes, targets):
    """Spec D5: amber LW_HAIR bus above the canopy, hairline drops into every
    listed compartment, source dot at the soma with a riser to the bus."""
    color = COLORS['scalar']
    xs = [nodes[t][0] for t in targets]
    top = max(nodes[t][1] for t in targets)
    y = top + f.fy(CONTACT_DIA_PT * 0.5 + 5.0)
    x_lo, x_hi = min(xs) - f.fx(2.0), max(xs) + f.fx(2.0)
    f.ax.plot([x_lo, x_hi], [y, y], color=color, lw=f.lw(LW_HAIR),
              solid_capstyle='round', zorder=5)
    for t in targets:
        px, py = nodes[t]
        f.arrow((px, y), (px, py + f.fy(2.8)), color=color, lw=LW_HAIR,
                head=2.6, zorder=5)
    sx, sy = nodes.soma
    src = (sx, sy + f.fy(nodes.soma_r_pt + 1.6))
    f.ax.plot([sx, sx], [src[1], y], color=color, lw=f.lw(LW_HAIR),
              solid_capstyle='round', zorder=1.8)
    f.disc(src, 1.6, fill=color, zorder=6)


def open_head(f, p0, p1, color):
    """The library's LW_EDGE '-|>' arrowhead, white-faced: a gated (x 0) entry."""
    width = f.lw(LW_EDGE)
    arr = FancyArrowPatch(
        p0, p1, arrowstyle='-|>,head_length=3.20,head_width=1.92',
        mutation_scale=1.0, facecolor='white', edgecolor=color,
        linewidth=width, shrinkA=0, shrinkB=0, capstyle='round', zorder=4.6)
    f.ax.add_patch(arr)
    return arr


def plain_log_ticks(ax, ticks=LOG_TICKS):
    """Log-axis ticks printed as PT_TICK '1e−6' strings (spec 0.4.6)."""
    ax.set_yscale('log')
    ax.yaxis.set_major_locator(FixedLocator(list(ticks)))
    ax.set_yticks(list(ticks))
    ax.set_yticklabels([('1' if t == 1 else sci(t)) for t in ticks])
    ax.yaxis.set_minor_locator(NullLocator())
    ax.yaxis.set_minor_formatter(NullFormatter())


def badge_at(ax, xy, kind, *, xycoords, offset_pt, ha, va):
    """``Frame.badge`` styling on a data axes (no Frame: it would hide the axes)."""
    key, face, edge = BADGE_STYLE[kind]
    colour = label_color(COLORS[key], background=face)
    return ax.annotate(kind, xy=xy, xycoords=xycoords, xytext=offset_pt,
                       textcoords='offset points', fontsize=PT_SMALL,
                       color=colour, ha=ha, va=va, zorder=7,
                       annotation_clip=False,
                       bbox=dict(boxstyle=f'round,pad=0.28,rounding_size={2.0 / PT_SMALL:.3f}',
                                 facecolor=face, edgecolor=edge, linewidth=LW_HAIR))


def seeds_and_mean(ax, x, values, mean, lo, hi, color, *, marker='D', fan=.09):
    values = np.asarray(values, float)
    ax.plot(x + np.linspace(-fan, fan, len(values)), values, ls='none', marker='o',
            ms=SEED_MS, mfc=color, mec='none', alpha=SEED_ALPHA, zorder=2)
    ax.errorbar(x, mean, yerr=[[mean - lo], [hi - mean]], fmt=marker, color=color,
                ms=MARKER_MS, mfc='white', mew=LW_ERR, elinewidth=LW_ERR,
                capsize=2, zorder=4)


# ── data --------------------------------------------------------------------
def nominal_teacher(opposed):
    """model.teacher's own gains with the log-normal perturbation set to zero."""
    class Silent:
        def normal(self, loc, scale, size):
            return np.zeros(size)
    with mock.patch.object(model.np.random, 'default_rng', lambda *a, **k: Silent()):
        return model.teacher(0, opposed)


def teacher_tuning():
    """Nominal terminal voltage against the latent feature, via model.forward."""
    z = np.linspace(-2.0, 2.0, 201)
    xx = np.tile(np.column_stack([z, z]), (1, 2))
    x = np.column_stack([np.exp(xx), np.exp(-xx), np.zeros((len(z), 2))])
    aligned = model.forward(nominal_teacher(False)[None], x)['voltage'][0]
    opposed = model.forward(nominal_teacher(True)[None], x)['voltage'][0]
    inc, dec = aligned[:, 0], opposed[:, 2]
    assert np.allclose(aligned[:, 2], inc) and np.allclose(opposed[:, 0], inc)
    xp, xm = np.exp(z), np.exp(-z)                       # report.py closed form
    assert np.allclose(inc, (8 * xp + .25 * xm) / (1 + 8 * xp + .25 * xm + .25 * xp + 8 * xm))
    assert np.allclose(dec, (.25 * xp + 8 * xm) / (1 + .25 * xp + 8 * xm + 8 * xp + .25 * xm))
    assert np.all(np.diff(inc) > 0) and np.all(np.diff(dec) < 0)
    table = pd.DataFrame(dict(z=z, v_increasing=inc, v_decreasing=dec))
    table.to_csv(FIG / 'teacher_tuning_source.csv', index=False)
    return table


def load_tables():
    read = lambda p: pd.read_csv(p, float_precision='round_trip')  # noqa: E731
    t = dict(band=read(FIG / 'curve_band_source.csv'),
             means=read(OUT / 'summaries/condition_means.csv'),
             endpoints=read(OUT / 'summaries/all_endpoints.csv'),
             contrasts=read(OUT / 'summaries/paired_contrasts.csv'),
             seed_contrasts=read(OUT / 'summaries/paired_seed_contrasts.csv'),
             historical=read(FIG / 'historical_cancellation_source.csv'))
    ep = t['endpoints']
    for task in ('aligned_strong', 'opposed_strong'):
        for rule in CURVE_RULES:
            b = t['band'][(t['band'].task == task) & (t['band'].rule == rule) & (t['band'].rate == PRIMARY['rate'])]
            assert len(b) == 12 and b.step.min() == 0 and b.step.max() == 16384
            assert not (b['mean'] < b.ci_low).any() and not (b['mean'] > b.ci_high).any()
    for rule in RULES:
        if rule == 'calibrated_broadcast':
            continue
        f = ep[(ep.task == 'opposed_strong') & (ep.rate == PRIMARY['rate']) & (ep.budget == PRIMARY['budget']) & (ep.rule == rule)]
        m = t['means'][(t['means'].task == 'opposed_strong') & (t['means'].rate == PRIMARY['rate']) & (t['means'].budget == PRIMARY['budget']) & (t['means'].rule == rule)]
        assert len(f) == 20 and f.seed.nunique() == 20 and len(m) == 1 and int(m.iloc[0].n) == 20
        assert abs(f.test_nmse.mean() - m.iloc[0]['mean']) < 1e-12
    return t


def cond(t, task, rule, budget=PRIMARY['budget']):
    m = t['means']
    return m[(m.task == task) & (m.rate == PRIMARY['rate']) & (m.budget == budget) & (m.rule == rule)].iloc[0]


# ── A: task schematic with the nominal-teacher inset ──────────────────────
def panel_task(ax, tuning):
    f = Frame(ax)
    core = f.task_card((0.0, 0.0, 1.0, 1.0),
                       footer='24 plastic conductances; context flips each example')
    x0, y0, w, h = core
    core_w, core_h = w * f.w_pt, h * f.h_pt
    iw, ih = 52.0, 34.0                             # inset, lower right (spec A)
    # tree: left of the inset, with a 30-pt band above the canopy for the two
    # staggered rows of stream tags and the subtree tags
    tree = (x0 + f.fx(8.0), y0 + f.fy(12.0), f.fx(96.0), h - f.fy(12.0 + 30.0))
    nodes = f.balanced_tree(tree, depth=2, trunk=False, mode='forward', output='',
                            capsules=list(SUBTREE))
    sx, sy = nodes.soma
    f.subscript((sx + f.fx(nodes.soma_r_pt + 1.5 + 11.0 + 2.5), sy), 'V', 's', ha='left')
    for t in nodes.terminals:                       # inh contact on each terminal branch
        f.contact(_lerp(nodes[nodes.parent[t]], nodes[t], 0.70), kind='inh')
    f.gate(nodes['JL'], closed=False, nodes=nodes, node='JL')
    f.gate(nodes['JR'], closed=True, descendants=['JR'], nodes=nodes, node='JR')
    f.error_in(nodes.soma, side='right')
    gate = COLORS['gate']
    jl, jr = nodes['JL'], nodes['JR']
    f.subscript(f._off(jl, -4.6, -12.0), 'a', 'p', ' = 0', color=gate, ha='right', va='top')
    f.subscript(f._off(jr, 4.6, -12.0), 'a', 'p', ' = 10', color=gate, ha='left', va='top')
    # stream tags: exp(±z1) feeds T1 and T3, exp(±z2) feeds T2 and T4.  Four
    # 32-pt tags over terminals 30 pt apart cannot share one line, so T1/T3
    # sit on the first row above the canopy and T2/T4 on the second; the
    # outer tags are anchored inward so nothing leaves the card.
    top = max(nodes[t][1] for t in nodes.terminals)
    lift = CONTACT_DIA_PT * 0.5 + 3.0
    rows = {'T1': 0, 'T3': 0, 'T2': 1, 'T4': 1}
    anchors = {'T1': ('left', -6.0), 'T2': ('center', 0.0), 'T3': ('center', 0.0),
               'T4': ('right', 6.0)}
    for t, sub in zip(nodes.terminals, ('1', '2', '1', '2')):
        ha, dx = anchors[t]
        f.subscript((nodes[t][0] + f.fx(dx), top + f.fy(lift + 9.0 * rows[t])),
                    'exp(±z', sub, ')', size=PT_SMALL, ha=ha, va='bottom')
    for (root, cname), tag in zip(SUBTREE, ('subtree 1', 'subtree 2')):
        terms = nodes.terminals_under(root)
        cx = np.mean([nodes[t][0] for t in terms])
        f.text((cx, top + f.fy(lift + 19.0)), tag, size=PT_SMALL,
               color=label_color(COLORS[cname]), va='bottom')
    # inset: nominal teacher terminal voltage against the latent feature
    rect = (x0 + w - f.fx(iw + 3.0), y0 + f.fy(20.0), f.fx(iw), f.fy(ih))
    inner = f.axes_inset(rect)
    inner.plot(tuning.z, tuning.v_increasing, color=INK, lw=LW_REF, zorder=3)
    dec, = inner.plot(tuning.z, tuning.v_decreasing, color=INK, lw=LW_REF, zorder=3)
    dec.set_dashes((2.2, 1.8))
    z_end = 1.82
    for col, cname in (('v_increasing', 'dend'), ('v_decreasing', 'soma')):
        y = float(np.interp(z_end, tuning.z, tuning[col]))
        inner.plot([z_end], [y], marker='s', ms=6.0, mfc=COLORS[cname], mec='none',
                   ls='none', clip_on=False, zorder=4)
    inner.set_xlim(-2.0, 2.0)
    inner.set_ylim(0.0, 1.0)
    inner.set_xticks([-2, 2], ['−2', '2'])
    inner.set_yticks([0, 1], ['0', '1'])
    inner.tick_params(labelsize=PT_TICK, pad=1.5)
    inner.text(0.0, 0.06, 'z', fontsize=PT_TICK, color=INK, ha='center', va='bottom')
    f.text((x0 + w - f.fx(3.0), rect[1] + f.fy(ih + 4.0)), 'opposed flips\nsubtree 2',
           size=PT_SMALL, ha='right', va='bottom', linespacing=1.15)
    return nodes


# ── B: the four deliveries ────────────────────────────────────────────────
def card_tree(f, cell):
    """Ghost copy of A's tree with the closed gate at J2 and δ0 (spec B)."""
    x0, y0, w, h = cell
    rect = (x0 + f.fx(2.0), y0 + f.fy(9.5), f.fx(50.0), h - f.fy(9.5 + 4.0))
    nodes = f.balanced_tree(rect, depth=2, trunk=False, mode='plain', ghost=True)
    # the double ring alone marks the closed gate: a 'c' badge lands on the
    # exact card's alpha tag at this 11-pt pitch (text is dropped, never shrunk)
    f.gate(nodes['JR'], closed=True, descendants=['JR'], nodes=nodes, node='JR', badge=None)
    sx, sy = nodes.soma
    x1 = sx + f.fx(nodes.soma_r_pt + 1.5)
    f.arrow((x1, sy), (x1 + f.fx(11.0), sy), color=MUTE, lw=LW_EDGE, head=3.4, zorder=4.5)
    f.error_in(nodes.soma, side='right')
    return nodes


def key_lines(f, cell, lines):
    x0, y0, w, h = cell
    x = x0 + f.fx(55.0)
    y = y0 + h - f.fy(5.0)
    for parts, color in lines:
        chain(f, (x, y), parts, size=PT_SMALL, color=color, ha='left', va='center')
        y -= f.fy(9.0)


def panel_deliveries(ax):
    f = Frame(ax)
    band = 12.0
    chain(f, (0.5, f.fy(band * 0.45)),
          ['E tests two controls: swapped gate 1[', ('a', 'p'),
           ' = 10]; proximal gate also at J1, J2'], size=PT_SMALL, color=MUTE, ha='center')
    gap_x, gap_y = f.fx(8.0), f.fy(5.0)
    cw, ch = (1.0 - gap_x) / 2.0, (1.0 - f.fy(band + 1.0) - gap_y) / 2.0
    y_top, y_bot = f.fy(band + 1.0) + ch + gap_y, f.fy(band + 1.0)
    cells = {'hero': (0.0, y_top, cw, ch), 'exact': (cw + gap_x, y_top, cw, ch),
             'broadcast': (0.0, y_bot, cw, ch), 'oracle': (cw + gap_x, y_bot, cw, ch)}
    shunting = COLORS['shunting']
    # hero: local distal gate
    cell = cells['hero']
    core = f.task_card(cell, title='Local distal gate', emphasis=True)
    f.badge((cell[0] + cell[2] - f.fx(4.0), cell[1] + cell[3] - f.fy(3.5)), 'local rule')
    nodes = card_tree(f, core)
    f._capsule(nodes, 'JL', 'dend')
    f.arrow(_lerp(nodes.soma, nodes['JL'], 0.40), _lerp(nodes.soma, nodes['JL'], 0.80),
            color=shunting, lw=LW_EDGE, head=4.0, zorder=4.6)
    open_head(f, _lerp(nodes.soma, nodes['JR'], 0.40), _lerp(nodes.soma, nodes['JR'], 0.80), shunting)
    key_lines(f, core, [(['distal × 1[', ('a', 'p'), ' = 0]'], INK),
                        (['J1, J2, soma × 1'], INK),
                        (['context and local'], MUTE), (['eligibility only'], MUTE)])
    # exact path
    cell = cells['exact']
    core = f.task_card(cell, title='Exact path')
    f.badge((cell[0] + cell[2] - f.fx(4.0), cell[1] + cell[3] - f.fy(3.5)), 'exact')
    nodes = card_tree(f, core)
    f.credit_delivery(nodes, mode='exact', targets=['T1', 'T4'])
    f.credit_delivery(nodes, mode='exact', targets=['T2', 'T3'], alpha_tags=True)
    key_lines(f, core, [(['distal × ', ('α', '1'), ('α', '2')], INK),
                        (['proximal × ', ('α', '1')], INK), (['soma × 1'], INK),
                        (['context sets ', ('α', '2')], MUTE)])
    # unit broadcast
    cell = cells['broadcast']
    core = f.task_card(cell, title='Unit broadcast')
    nodes = card_tree(f, core)
    amber_bus(f, nodes, ['T1', 'T2', 'JL', 'JR', 'T3', 'T4'])
    key_lines(f, core, [(['all seven sites × 1'], INK),
                        (['one scalar for all'], MUTE)])
    # two-leaf oracle
    cell = cells['oracle']
    core = f.task_card(cell, title='Two-leaf oracle')
    f.badge((cell[0] + cell[2] - f.fx(4.0), cell[1] + cell[3] - f.fy(3.5)), 'oracle')
    nodes = card_tree(f, core)
    for root, cname in SUBTREE:
        f._capsule(nodes, root, cname)
        f.arrow(_lerp(nodes.soma, nodes[root], 0.40), _lerp(nodes.soma, nodes[root], 0.80),
                color=COLORS['oracle'], lw=LW_EDGE, head=4.0, zorder=4.6)
    key_lines(f, core, [(['subtree 1 × ', ('ĉ', '1')], INK), (['subtree 2 × ', ('ĉ', '2')], INK),
                        (['J1, J2, soma × 1'], INK),
                        (['ĉ from the exact field'], MUTE)])


# ── C / D: learning curves ───────────────────────────────────────────────
def curves(ax, t, task, *, legend=False, shared=False):
    band = t['band']
    ends = {}
    for rule in CURVE_RULES:
        b = band[(band.task == task) & (band.rule == rule) & (band.rate == PRIMARY['rate'])].sort_values('step')
        color = rc(rule)
        ax.fill_between(b.step, b.ci_low, b.ci_high, color=color, alpha=.14, lw=0, zorder=1)
        ax.plot(b.step, b['mean'], color=color, lw=LW_DATA, zorder=3, label=RULES[rule][0])
        ends[rule] = b
    ax.set_xscale('symlog', linthresh=64)
    ax.set_xlim(0, 16384)
    # a '4,096' tick 35 pt from '16,384' collides at PT_TICK, so the primary
    # window is named on its dashed reference instead
    ax.set_xticks([0, 64, 1024, 16384], ['0', '64', '1,024', '16,384'])
    ax.xaxis.set_minor_locator(NullLocator())
    plain_log_ticks(ax)
    ax.set_ylim(*LOG_YLIM)
    ax.set_xlabel('Updates')
    ax.xaxis.labelpad = 2.5
    reference_line(ax, PRIMARY['budget'], axis='x', label=None, span=LOG_YLIM)
    ax.annotate(f"{PRIMARY['budget']:,}", xy=(PRIMARY['budget'], LOG_YLIM[1]),
                xytext=(1.4, 0.0), textcoords='offset points', fontsize=PT_SMALL,
                color=MUTE, ha='left', va='top', zorder=5, annotation_clip=False)
    style_panel(ax)
    ax.tick_params(axis='x', pad=2.0)
    ax.get_xticklabels()[-1].set_ha('right')
    if shared:                                  # D shares C's axis: ticks, no labels
        ax.tick_params(axis='y', labelleft=False)
    else:
        ax.set_ylabel('Held-out NMSE')
    if legend:
        handles = [Line2D([], [], color=rc(r), lw=LW_DATA, label=RULES[r][0]) for r in CURVE_RULES]
        # lower left: the only quadrant the four descending curves leave empty
        leg = ax.legend(handles=handles, loc='lower left', frameon=False, fontsize=PT_LEGEND,
                        handlelength=1.5, handletextpad=.6, labelspacing=.3, borderaxespad=.2)
        ax._oracle_entry = leg.get_texts()[CURVE_RULES.index('ancestry_two_leaf_oracle_unit_proximal')]
    return ends


def curve_labels(ax, t):
    """D's direct labels, derived from condition_means at the primary window."""
    bc = cond(t, 'opposed_strong', 'unit_broadcast')['mean']
    trio = [cond(t, 'opposed_strong', r)['mean'] for r in CURVE_RULES if r != 'unit_broadcast']
    assert max(trio) < 3e-5 and abs(bc - 0.487) < 5e-3
    ax.text(3300, 0.95, f'broadcast {bc:.2f}', ha='right', va='bottom', fontsize=PT_ANNOT,
            color=AMBER_TEXT, zorder=6)
    ax.text(64, 3.0e-6, f'exact, gate, oracle ≈ {sci(np.mean(trio))}', ha='left', va='center',
            fontsize=PT_ANNOT, color=INK, zorder=6)
    ax.plot([2700, 4096], [6.5e-6, 1.5e-5], color=MUTE, lw=LW_HAIR, zorder=2)
    return dict(broadcast=float(bc), trio=[float(v) for v in trio])


# ── E: gate placement ─────────────────────────────────────────────────────
E_ORDER = ('exact', 'hard_distal_unit_proximal', 'swapped_distal_unit_proximal', 'hard_distal_and_proximal')
E_LABELS = ('Exact\npath', 'Distal\ngate', 'Swapped\ngate', 'Also\nproximal')
# 'Gate also / proximal' (32 pt) beside 'Swapped' (31 pt) cannot share a
# 28-pt category pitch at PT_SMALL; the fourth category reads 'Also proximal'.


def placement(ax, t):
    ep = t['endpoints']
    printed = {}
    for i, rule in enumerate(E_ORDER):
        f = ep[(ep.task == 'opposed_strong') & (ep.rate == PRIMARY['rate']) & (ep.budget == PRIMARY['budget']) & (ep.rule == rule)].sort_values('seed')
        m = cond(t, 'opposed_strong', rule)
        seeds_and_mean(ax, i, f.test_nmse, m['mean'], m.ci_low, m.ci_high, rc(rule))
        printed[rule] = dict(mean=float(m['mean']), ci_low=float(m.ci_low), ci_high=float(m.ci_high),
                             g_i0_changed=int(f.g_i0_changed.sum()), g_i1_changed=int(f.g_i1_changed.sum()),
                             both_frozen=int((~f.g_i0_changed & ~f.g_i1_changed).sum()), n=int(len(f)))
    frozen = printed['hard_distal_and_proximal']['both_frozen']
    assert frozen == 20 and printed['swapped_distal_unit_proximal']['g_i0_changed'] == 16
    bc = cond(t, 'opposed_strong', 'unit_broadcast')['mean']
    ax.set_xlim(-.3, 3.45)                   # >= 31-pt category pitch, no overhang
    plain_log_ticks(ax)
    ax.set_ylim(*LOG_YLIM)
    reference_line(ax, bc, label=None)
    ax.annotate(f'broadcast {bc:.2f}', xy=(-.3, bc), xytext=(1.4, 1.4), textcoords='offset points',
                fontsize=PT_SMALL, color=MUTE, ha='left', va='bottom', zorder=5)
    ax.set_xticks(range(4), E_LABELS)
    ax.tick_params(axis='x', labelsize=PT_SMALL, pad=2.0)
    ax.set_ylabel('Opposed NMSE')
    style_panel(ax)
    token_subscript(ax, 1.2, 2.2e-3, 'g', 'I', f' frozen {frozen}/20', size=PT_ANNOT, ha='left')
    ax.plot([3.0, 3.0], [3.3e-3, 5.5e-3], color=MUTE, lw=LW_HAIR, zorder=2)
    return printed


# ── F: the primary estimand ───────────────────────────────────────────────
def interaction(ax, t):
    c, s = t['contrasts'], t['seed_contrasts']
    color = COLORS['shunting']
    printed = {}
    for i, budget in enumerate((4096, 16384)):
        sel = (s.task == 'opposed_minus_aligned') & (s.rate == PRIMARY['rate']) & (s.budget == budget) & (s.left == 'unit_broadcast') & (s.right == 'hard_distal_unit_proximal')
        vals = s[sel].sort_values('seed').difference
        m = c[(c.task == 'opposed_minus_aligned') & (c.rate == PRIMARY['rate']) & (c.budget == budget) & (c.left == 'unit_broadcast') & (c.right == 'hard_distal_unit_proximal')].iloc[0]
        assert len(vals) == 20 and abs(vals.mean() - m['mean']) < 1e-12 and int(m.positive) == int((vals > 0).sum())
        seeds_and_mean(ax, i, vals, m['mean'], m.ci_low, m.ci_high, color)
        printed[str(budget)] = dict(mean=float(m['mean']), ci_low=float(m.ci_low), ci_high=float(m.ci_high), positive=int(m.positive))
    ax.set_xlim(-.5, 1.5)
    ax.set_ylim(*UNIT_YLIM)
    ax.set_yticks([0, .5, 1], ['0', '0.5', '1'])
    ax.set_xticks([0, 1], ['4,096', '16,384'])
    reference_line(ax, 0.0, label=None)
    ax.annotate('no interaction', xy=(1.5, 0.0), xytext=(0.0, -1.4), textcoords='offset points',
                fontsize=PT_SMALL, color=MUTE, ha='right', va='top', zorder=5)
    ax.set_xlabel('Window (updates)')
    # one-line y label (a second line pushes the F letter onto E's axes
    # corner); the opposed − aligned qualifier is the in-panel note
    ax.set_ylabel('Broadcast − gate NMSE')
    style_panel(ax)
    pos = ', '.join(f'{printed[str(b)]["positive"]}/20' for b in (4096, 16384))
    ax.text(0.5, 1.42, f'opposed − aligned;\npositive in {pos} seeds', ha='center', va='top',
            fontsize=PT_SMALL, color=MUTE, linespacing=1.15)
    return printed


# ── G: context-gradient cancellation (earlier cohort) ─────────────────────
def cancellation(ax, t):
    h = t['historical']
    assert len(h) == 80 and set(h.historical_seed) == set(range(2101, 2121))
    rng = np.random.default_rng(HIST_SEED)
    printed = {}
    for rule, offset, marker, color in (('exact', -.12, 'o', COLORS['bp']),
                                        ('calibrated_broadcast', .12, 's', COLORS['per_soma'])):
        means = []
        for i, state in enumerate(('initial', 'extended_best')):
            part = h[(h.state == state) & (h.evaluated_rule == rule) & (h.source_rule == 'calibrated_broadcast')].sort_values('historical_seed')
            assert len(part) == 20
            vals = part.context_cancellation_ratio.to_numpy()
            lo, hi = boot(vals, rng)
            seeds_and_mean(ax, i + offset, vals, vals.mean(), lo, hi, color, marker=marker)
            means.append(vals.mean())
            printed[f'{rule}_{state}'] = dict(mean=float(vals.mean()), ci_low=float(lo), ci_high=float(hi))
        ax.plot([offset, 1 + offset], means, color=color, lw=LW_HAIR, zorder=3)
    assert abs(printed['exact_initial']['mean'] - 0.636) < 2e-3 and abs(printed['calibrated_broadcast_extended_best']['mean'] - 0.172) < 2e-3
    ax.set_xlim(-.5, 1.5)
    ax.set_ylim(*UNIT_YLIM)
    ax.set_yticks([0, .5, 1], ['0', '0.5', '1'])
    ax.set_xticks([0, 1], ['Initial', 'Broadcast-\ntrained'])
    ax.tick_params(axis='x', labelsize=PT_SMALL, pad=2.0)
    reference_line(ax, 1.0, label='no cancellation')
    ax.set_ylabel('Gradient retained')
    style_panel(ax)
    ax.text(0.40, 0.55, 'exact', ha='center', va='center', fontsize=PT_LEGEND, color=COLORS['bp'])
    # the only band free of seeds is under the two clusters, so the label
    # runs along the axis floor beside the calibrated squares
    ax.text(0.85, -0.13, 'calibrated broadcast', ha='center', va='center', fontsize=PT_LEGEND,
            color=label_color(COLORS['per_soma']))
    ax.text(-.42, 1.42, 'earlier cohort, seeds 2101–2120;\ncalibrated broadcast', ha='left', va='top',
            fontsize=PT_SMALL, color=MUTE, linespacing=1.15)
    return printed


# ── assembly ──────────────────────────────────────────────────────────────
def build(cfg, tables, tuning):
    canvas = NativeCanvas(HEIGHT_PT / 72, 3, row_weights=ROWS_PT, hgutter_pt=HGUTTER_PT,
                          vgutter_pt=VGUTTER_PT, margins=Margins(**MARGINS))
    a = canvas.panel('A', 0, 0, 5, schematic=True, lock=False, title='Context shunts one branch')
    b = canvas.panel('B', 0, 5, 7, schematic=True, lock=False, title='Four ways to deliver the somatic error')
    c = canvas.panel('C', 1, 0, 6, title='Aligned: all rules learn')
    d = canvas.panel('D', 1, 6, 6, title='Opposed: broadcast fails')
    e = canvas.panel('E', 2, 0, 4, title='Gate placement decides')
    f_ = canvas.panel('F', 2, 4, 4, title='Task-specific gate benefit')
    g = canvas.panel('G', 2, 8, 4, title='Context gradients cancel')
    panel_task(a, tuning)
    panel_deliveries(b)
    curves(c, tables, 'aligned_strong', legend=True)
    curves(d, tables, 'opposed_strong', shared=True)
    printed = dict(D=curve_labels(d, tables), E=placement(e, tables), F=interaction(f_, tables),
                   G=cancellation(g, tables))
    # oracle badge after C's legend entry text, anchored in points to the axes corner
    canvas.fig.canvas.draw()
    r = canvas.fig.canvas.get_renderer()
    box = c._oracle_entry.get_window_extent(r)
    corner = c.transAxes.transform((0.0, 0.0))
    k = 72.0 / canvas.fig.dpi
    badge_at(c, (0.0, 0.0), 'oracle', xycoords='axes fraction',
             offset_pt=((box.x1 - corner[0]) * k + 3.0, ((box.y0 + box.y1) / 2 - corner[1]) * k),
             ha='left', va='center')
    # One axes width per span family (strict audit 'row-alignment'): reserves
    # are locked per grid column, so a right-side need of G (column 12) would
    # narrow D but not C.  Declare the widest left / right need of any data
    # panel for all of them, so C = D and E = F = G exactly.
    canvas.lock_reserves()
    data_panels = ('C', 'D', 'E', 'F', 'G')
    left = max(canvas._locks[n][0] for n in data_panels)
    right = max(canvas._locks[n][1] for n in data_panels)
    # A mid-row letter sits 36 pt left of its panel's y-label stack, i.e. on
    # the 38-pt gutter's far edge: a 4-pt right reserve keeps the F and G
    # letters clear of E's and F's title boxes (align_letters).
    right = max(right, 4.0)
    # row 2 letters must sit >= 8.5 pt below row 1's x labels (audit_row_separation)
    row2_top = max(canvas._locks[n][2] for n in ('E', 'F', 'G')) + 5.0
    for n in data_panels:
        canvas.declare_reserve(n, left=left, right=right,
                               top=row2_top if n in ('E', 'F', 'G') else canvas._locks[n][2],
                               bottom=canvas._locks[n][3])
    canvas.lock_reserves()
    findings = list(canvas.align_letters())
    problems = findings + list(canvas.save(PDF, name='local_gate_primary', dpi=180))
    audit = [str(v) for v in audit_native_pdf(PDF, strict=True)]
    return printed, problems, audit


def figure_provenance(cfg, printed, problems, audit):
    """Record present render inputs separately from the immutable initial audit."""
    files = [FIG / name for name in ['local_gate_primary.pdf', 'local_gate_primary.png', 'local_gate_all_rates.pdf',
                                     'local_gate_all_rates.png', 'curve_band_source.csv',
                                     'historical_cancellation_source.csv', 'teacher_tuning_source.csv']]
    inputs = list(sorted((OUT / 'summaries').glob('*.csv'))) + [OUT / 'protocol.json', OUT / 'protocol_freeze.json',
                                                                 J / 'source_data/conductance_credit_demand/opponent/summaries/context_gradient_summary.csv']
    code = [Path(__file__), Path(__file__).with_name('report.py'), Path(__file__).with_name('portable_contract.py'),
            Path(__file__).with_name('model.py'), J / 'scripts/journal_style.py', J / 'scripts/figure_canvas.py',
            J / 'scripts/native_schematics.py', J / 'scripts/credit_tree_schematics.py']

    def hashes(paths):
        return {str(p.relative_to(J)): digest(p) for p in paths}
    record = dict(
        status='PASS',
        scope='Current figure-only rendering; frozen protocol and numerical summary bytes unchanged. Initial numerical audit retains its historical render hashes.',
        protocol_sha256=digest(OUT / 'protocol.json'), fresh_seeds=cfg['fresh_seeds'],
        historical_seeds=list(range(2101, 2121)), figure_sha256=hashes(files), input_sha256=hashes(inputs),
        code_sha256=hashes(code),
        panel_sources={
            'main_5A': {'type': 'model schematic with nominal teacher tuning', 'sources': ['scripts/conductance_local_gate/model.py', 'source_data/conductance_local_gate/figures/teacher_tuning_source.csv'], 'scope': 'Seven-compartment tree, context gate, local distal gate vocabulary; inset: nominal unperturbed teacher terminal voltage against the latent feature (model.forward on model.teacher gains with zero perturbation), not fitted student results.'},
            'main_5B': {'type': 'rule schematic', 'sources': ['scripts/conductance_local_gate/model.py', 'source_data/conductance_local_gate/METHODS.md'], 'scope': 'Delivered-credit multipliers of model.delivered for the local distal gate, exact path, unit broadcast and two-leaf oracle; no experimental outcomes.'},
            'main_5C_D': {'type': 'fresh cohort', 'sources': ['source_data/conductance_local_gate/summaries/all_curves.csv', 'source_data/conductance_local_gate/figures/curve_band_source.csv', 'source_data/conductance_local_gate/summaries/condition_means.csv'], 'scope': 'Adam 0.03; four prespecified rules; all twenty fresh seeds; aligned (C) and opposed (D) targets. Display ribbons are descriptive 20000-resample seed-bootstrap intervals, separate RNG 2026090830; D direct labels from condition_means at the 4,096-update window.'},
            'main_5E': {'type': 'fresh cohort', 'sources': ['source_data/conductance_local_gate/summaries/all_endpoints.csv', 'source_data/conductance_local_gate/summaries/condition_means.csv'], 'scope': 'Primary-rate opposed endpoints at the 4,096-update window: exact, local distal gate, swapped gate and proximal-gating failure control; inhibitory-gain change counts from all_endpoints; broadcast mean as the dashed reference.'},
            'main_5F': {'type': 'fresh cohort', 'sources': ['source_data/conductance_local_gate/summaries/paired_seed_contrasts.csv', 'source_data/conductance_local_gate/summaries/paired_contrasts.csv'], 'scope': 'Paired task-by-rule interaction (opposed minus aligned difference of broadcast minus local-gate NMSE) at the primary and extended validation windows.'},
            'main_5G': {'type': 'historical cohort', 'sources': ['source_data/conductance_credit_demand/opponent/summaries/context_gradient_summary.csv', 'source_data/conductance_local_gate/figures/historical_cancellation_source.csv'], 'scope': 'Earlier seeds 2101–2120; opposed task; calibrated-broadcast source weights; exact and calibrated evaluations; fraction of the distal parameter gradient retained after context averaging at initial and extended-best states. Copy of Supplementary Fig. S53E; does not evaluate new local-gate fits.'},
            'supp_53A_D': {'type': 'fresh cohort', 'sources': ['source_data/conductance_local_gate/summaries/condition_means.csv'], 'scope': 'All nine rules, three rates, two tasks and two validation windows; 1080 trajectories and 2160 endpoint views.'},
            'supp_53E': {'type': 'historical cohort', 'sources': ['source_data/conductance_credit_demand/opponent/summaries/context_gradient_summary.csv', 'source_data/conductance_local_gate/figures/historical_cancellation_source.csv'], 'scope': 'Earlier seeds 2101–2120; opposed task; calibrated-broadcast source weights; exact and calibrated evaluations; distal parameter gradients at initial and extended-best states. Does not evaluate new local-gate fits.'}},
        printed_numbers=printed,
        native_canvas=dict(height_pt=HEIGHT_PT, rows_pt=list(ROWS_PT), layout_findings=problems, strict_audit_violations=audit),
    )
    record['source_sha256'] = {**record['input_sha256'], **record['code_sha256']}
    (OUT / 'figure_provenance.json').write_text(json.dumps(record, indent=2, sort_keys=True) + '\n')


def main():
    cfg, freeze, _ = load_protocol()
    audit = json.loads((OUT / 'summaries/completeness_audit.json').read_text())
    assert audit['status'] == 'PASS'
    folder = OUT / 'summaries'
    for relative, original in audit['summary_sha256'].items():
        verify(OUT / relative, original)
    frames = {k: pd.read_csv(folder / f'all_{k}.csv', float_precision='round_trip') for k in ['endpoints', 'curves', 'diagnostics']}
    means = pd.read_csv(folder / 'condition_means.csv', float_precision='round_trip')
    contrasts = pd.read_csv(folder / 'paired_contrasts.csv', float_precision='round_trip')
    # Supplementary all-rates figure + render CSVs exactly as before; the old
    # gridspec main figure that report.figures also emits is not written, so
    # the output path never holds a pre-canvas render, even transiently.
    import report
    _save = report.save

    def save_all_rates_only(fig, name):
        if name == 'local_gate_primary':
            matplotlib.pyplot.close(fig)
            return
        _save(fig, name)
    with mock.patch.object(report, 'save', save_all_rates_only):
        figures(cfg, frames, means, contrasts)
    tuning = teacher_tuning()
    tables = load_tables()
    printed, problems, strict = build(cfg, tables, tuning)
    figure_provenance(cfg, printed, problems, strict)
    for line in problems:
        print('layout:', line)
    for line in strict:
        print('strict audit:', line)
    print('Native figures redrawn; experiment protocol and numerical summary files unchanged.')


if __name__ == '__main__':
    main()
