#!/usr/bin/env python3
"""Main Fig. 5 (v2 overhaul): a local distal gate in a conductance tree.

Builds ``figures/main/figure_05.pdf`` (label ``fig:conductancecredit``) from
``analysis/figure_overhaul_20260908/v2/fig5/PLAN.md`` as amended by
``v2/AMENDMENTS.md`` and ruled by ``v2/DECISIONS.md``.  Nothing is trained and
no frozen protocol or summary file is written: the frozen protocol and every
numerical summary are verified byte-for-byte before anything is read
(``portable_contract.verify``), the Supplementary all-rates figure is
regenerated by ``report.figures`` exactly as before, and the main figure is
then drawn on the ``NativeCanvas``.

Cross-figure rules (AMENDMENTS §3) this builder is held to
--------------------------------------------------------
CF-1  canvas 518.4 x 490.0 pt, aspect 1.058, height on the 340/415/490 ladder.
CF-2  exactly three type sizes 7.0 / 8.0 / 9.0-bold, nothing below 7.0, no
      DejaVu, sub/superscripts as token chains and never mathtext.
CF-3  strokes only .55/.7/.85/.95/1.25 pt; every area mark a 16 % tint patch
      with a 0.55 pt edge; no open stroke at or above 1.35 pt.
CF-4  soma lowest and filled, canopy up, white junction rings, filled exc/inh
      contacts, the gate family as contact + ring + 7 pt badge (no bars),
      attenuation at 38 %, ghosts at 45 %, exactly the four delivery modes,
      one ink delta-0 arrow into every soma and NO delta-0 exemption here.
CF-5  zero legend boxes; the frameless four-entry rule key inside panel C is
      the ONE sanctioned in-axes key in the whole nine-figure set.
CF-6  the forest idiom does not apply: Fig 5 is one of the two figures that
      use no ``forest()`` (plan decision F1, ratified by CF-6).
CF-7  every reference line dashed mute at LW_REF with its label on the line
      (E's 'no interaction', F's 'unit broadcast 0.49', G's 'no cancellation');
      the window rule of C and D is the same dash at the same weight, cut
      where a text span crosses it.
CF-9  titles sentence case, finding phrases, no method-naming exception here.
CF-10 schematic area on the B12 formula
      ``sum(schematic slot w x h) / (live_w x live_h)`` with live = 450.4 x 436:
      (165.5 + 246.9) x 108 / 196374.4 = 22.7 %, inside the 30 % cap.  The
      DECISIONS G4 waiver for Fig 5 is restated and kept on record; it is a
      record, not an active exemption, because the figure passes without it.
CF-12 letters 9 pt bold on the module grid; ``align_letters()`` is called
      unconditionally by ``canvas.save()``.

Grid: ``NativeCanvas(490/72, 3, row_weights=[108, 122, 122], hgutter 38,
vgutter 42, margins 54/14/22/32)``; 22 + 108 + 42 + 122 + 42 + 122 + 32 = 490.
Left 54 and vgutter 42 are kept from v1 (the 37-pt y-label stacks of C and E
must clear the 16.8-pt letter column, and the gutter must hold a 23-pt
tick+x-label stack, the 13-pt letter band and the 8.5-pt row-separation
floor).  Row 0: A (5 modules) + B (7); row 1: C (6) + D (6) sharing the log
NMSE axis; row 2: E, F, G (4/4/4).

Private helpers (SPEC_ERRATA item 7 / DECISIONS G5; the library is not edited)
-----------------------------------------------------------------------------
``chain``/``chain_data``  token sub- and SUPERscript runs.  ``Frame.subscript``
    and ``figure_canvas.token_subscript`` draw subscripts only, and the
    journal face has no superscript-minus glyph, so ``10`` with a raised
    ``-6`` has to be composed here; nothing is mathtext and nothing is below
    7.0 pt.
``plain_log_ticks``  the same composition on a log axis: the tick label is the
    real tick text ``10`` (so the canvas measures the reserve) and the raised
    exponent is annotated into the pad it leaves.
``axis_break``       two hairline slashes on the spine at the linear/log join.
``window_rule``      the 4,096 reference in C and D, drawn last and stepped
    around every text span it would otherwise strike through (CF-7 keeps the
    label on the rule; it says nothing about a rule crossing a direct label,
    and a single full-height segment crossed four lines of type per panel).
``tie_leader``       the hairline from a tied annotation up to the lowest
    datum of the column it names (the plan's y_text < y_lead < lowest).
``badge_at``         ``Frame.badge`` styling on a data axes.
``subtree_delivery`` the library's ``credit_delivery(mode='subtree')``
    geometry with the capsule hue named by the caller.  ``credit_delivery``
    takes its capsule hues from ``K_CYCLE``, whose two-target entry is
    (shunting, additive); ``additive`` is Fig 4's calibrated-broadcast hue and
    AMENDMENTS §5 bans it from Fig 5.  The local-gate card uses this helper;
    the oracle instead uses ``distal_oracle_delivery`` to mark only its two
    distal supports, with no oracle multiplier at either proximal site.
``open_head``        the white-faced arrowhead of a credit path gated to zero.
``min_separation_pt`` point clearance between two artist groups (text on a
    frame is invisible to every audit).
"""
import hashlib
import json
import math
import sys
from pathlib import Path
from unittest import mock

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrowPatch
from matplotlib.ticker import FixedLocator, NullFormatter, NullLocator

from report import OUT, figures, boot
from portable_contract import J, load_protocol, verify
import model

sys.path.insert(0, str(J / 'scripts'))
from figure_canvas import (COLORS, LETTER_CAP_FRAC, LETTER_GAP_PT, LW_DATA,  # noqa: E402
                           LW_EDGE, LW_ERR, LW_HAIR, LW_REF, MARKER_MS,
                           PT_BASE, PT_EMPH, SEED_ALPHA, SEED_MS, Margins,
                           NativeCanvas, audit_native_pdf, style_panel)
from journal_style import label_color  # noqa: E402
from credit_tree_schematics import AMBER_TEXT, mix  # noqa: E402
from native_schematics import (BADGE_STYLE, CONTACT_DIA_PT, Frame, _lerp,  # noqa: E402
                               _text_w_pt, _wrap_to_width, reference_line)

sys.path.insert(0, str(J / 'scripts/credit_first_figures'))
import focused_provenance  # noqa: E402

FIG = OUT / 'figures'
PDF = FIG / 'local_gate_primary.pdf'
INK, MUTE = COLORS['ink'], COLORS['mute']
DASH = (0, (2.2, 1.8))

# ── frozen vocabulary (AMENDMENTS §4a) and the series register (§5) ───────
RULES = {
    'exact': ('Exact path', 'bp'),
    'hard_distal_unit_proximal': ('Local distal gate', 'shunting'),
    'shunt_proportional_unit_proximal': ('Local distal gate', 'shunting'),
    'unit_broadcast': ('Unit broadcast', 'scalar'),
    'ancestry_two_leaf_oracle_unit_proximal': ('Two-profile oracle', 'oracle'),
    'swapped_distal_unit_proximal': ('Swapped gate', 'point_mlp'),
    'hard_distal_and_proximal': ('Gate also proximal', 'highlight'),
    'calibrated_broadcast': ('Calibrated broadcast', 'scalar'),
}
CURVE_RULES = ('exact', 'hard_distal_unit_proximal', 'unit_broadcast',
               'ancestry_two_leaf_oracle_unit_proximal')
# QA 2026-09-10 (visual review).  Exact path, gate and oracle agree to within
# a tenth of a decade -- three points of line -- from step 256 on, so drawn
# as three opaque solids stacked in z order the last one painted hid the other
# two: a pixel census of the v1 render found no carmine at all in the left
# 64 % of C.  The panels' finding is that agreement, so the three are keyed by
# dash and the coincidence is shown.  QA 2026-09-11 (second visual pass): the
# painting order is inverted from the first fix.  Keying by dash is not enough
# on its own while the one OPAQUE SOLID of the trio is painted last: a census
# of that render still found the oracle's colour in only 37 of C's 410 columns
# and 6 of D's, because a solid carmine line covers a dotted line that lies
# inside its own width.  The solid goes to the BOTTOM instead -- exact path
# first, the gate's long dash over it, the oracle's fine dash on top -- so
# each of the three shows through the gaps of the ones above it and all three
# read wherever they coincide.  The dash key and the legend are unchanged; only
# the paint order moves, and no plotted value is touched.  Unit broadcast stays
# solid and goes to the very bottom: over the first two decades of C all FOUR
# rules coincide, so whichever solid is painted last owns that stretch, and put
# on top the amber one hid the trio there exactly as the carmine one had.  It
# has its own direct label and it separates from the trio well before the
# window, which is where its being read matters.  Mute reference rules keep
# their own dash at LW_REF (CF-7) and no data line is drawn in mute.
CURVE_DASH = {'hard_distal_unit_proximal': (3.4, 1.7),
              'ancestry_two_leaf_oracle_unit_proximal': (1.2, 1.5)}
CURVE_Z = {'unit_broadcast': 2.9, 'exact': 3.0,
           'hard_distal_unit_proximal': 3.1,
           'ancestry_two_leaf_oracle_unit_proximal': 3.2}
PRIMARY = dict(rate=0.03, budget=4096)
RATES = (0.01, 0.03, 0.10)
LOG_TICKS = (1e-6, 1e-4, 1e-2, 1.0)
# The aligned bands reach 3.5e-7, so the floor drops half a decade below the
# lowest printed tick.  The head was 1e3 because every on-panel note the plan
# mandates for C, D and F had to live inside the axes above the traces.
# QA 2026-09-10 (visual review): the notes that only repeated the caption
# (optimiser, n, bootstrap, seed range, P) are deleted and F's two shape keys
# move to the caption, so a decade of that head goes back to the data.  The
# head cannot fall further without moving C's sanctioned four-entry key (CF-5)
# out of the band above the traces: the highest datum is 1.27 and the key,
# D's two-line readout note and F's two column tags need ~20 pt above it.
# The tick set is unchanged, so C, D and F still share one ladder.
LOG_YLIM = (3e-7, 1e2)
# the window rule stops here, just above the highest trace, and every C/D text
# block is right-aligned at TEXT_RIGHT so nothing is struck through by it.
REF_TOP = 2.0
TEXT_RIGHT = 0.98
# E and G: the plan's head, now that the three-line note (E) and the two-line
# cohort tag (G) that filled the band above 1.0 are gone -- both only repeated
# the caption.  1.15 leaves 10 pt over the unit rule for G's 'no cancellation'
# label and E's single 'opposed - aligned' qualifier; the foot stays at -0.22,
# which is G's two-line 'calibrated broadcast' label, not empty axis.
UNIT_YLIM = (-0.22, 1.15)
HIST_SEED = 982211                      # descriptive bootstrap RNG, as report.py
ROWS_PT = [108, 122, 122]
VGUTTER_PT = 42
HGUTTER_PT = 38
MARGINS = dict(left=54, right=14, top=22, bottom=32)
LETTER_DX_PT = 26.0
# reserves are declared BEFORE anything is drawn: every width test in the
# panels (label wrapping, category pitch, direct-label anchors) is measured
# against the axes box, so the box has to be final first.  LEFT clears the
# letter column with the y-label stack inside the slot (audit_letter_align-
# ment); ROW2_TOP keeps the row-2 letters 8.5 pt below row 1's x labels.
# QA 2026-09-10 (visual review): 18.5, not 17.0 -- E's y label is two
# lines now that it names the double difference it plots, and the rotated
# stack needs 1.1 pt more than the old single line.  Declared for every
# data panel alike, so C = D and E = F = G stay exact.
LEFT_RESERVE_PT = 18.5
RIGHT_RESERVE_PT = 4.0
ROW2_TOP_PT = 5.7
HEIGHT_PT = MARGINS['top'] + sum(ROWS_PT) + 2 * VGUTTER_PT + MARGINS['bottom']
LIVE_W_PT = 518.4 - MARGINS['left'] - MARGINS['right']
LIVE_H_PT = HEIGHT_PT - MARGINS['top'] - MARGINS['bottom']
SCHEMATIC_FRACTION = (165.5 + 246.9) * ROWS_PT[0] / (LIVE_W_PT * LIVE_H_PT)
KEY_EXCEPTION = ('CF-5: the frameless four-entry rule key inside panel C is '
                 'the single sanctioned in-axes key in the nine-figure set; '
                 'C and D share four series across two panels.')
G4_WAIVER = (f'DECISIONS G4 schematic-area waiver for Fig 5, restated at the '
             f'AMENDMENTS B12 / CF-10 value {SCHEMATIC_FRACTION * 100:.1f} % '
             f'(sum of schematic slot areas over the live canvas '
             f'{LIVE_W_PT:.1f} x {LIVE_H_PT:.0f} pt). Recorded, not exercised: '
             f'the figure is inside the 30 % cap and no relaxation of '
             f'PANEL_ASPECT_MAX or of the cap is requested.')


def rc(key):
    return COLORS[RULES[key][1]]


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def true_minus(s):
    return str(s).replace('-', '−')


def round_half_up(v):
    return math.floor(float(v) + 0.5)


# ── private glyph helpers ─────────────────────────────────────────────────
def _parts_width(ax, parts, size=PT_BASE):
    """Width in points of a chain of str / ('sub'|'sup', s) tokens."""
    total = 0.0
    for p in parts:
        if isinstance(p, tuple):
            total += 0.4 + _text_w_pt(ax, p[1], size)
        else:
            total += _text_w_pt(ax, p, size)
    return total


def chain_data(ax, xy, parts, *, size=PT_BASE, color=None, ha='left',
               va='center', zorder=6, transform=None, drop_pt=1.6,
               rise_pt=2.4):
    """Plain strings and ('sub'|'sup', token) pairs laid out left to right.

    ``Frame.subscript`` (and ``figure_canvas.token_subscript``) draw a
    subscript only, and mathtext is banned by CF-2, so the superscript half of
    ``10`` with a raised exponent is composed here with the same geometry:
    every piece is a real 7.0-pt text span, offset in points from the piece
    before it.  Returns (artists, width_pt).
    """
    color = INK if color is None else color
    transform = ax.transData if transform is None else transform
    width = _parts_width(ax, parts, size)
    x, y = xy
    arts = []
    anchor = ax.text(x, y, '', fontsize=size, ha=ha, va=va,
                     transform=transform, clip_on=False)
    dx = {'left': 0.0, 'center': -width / 2.0, 'right': -width}[ha]
    for p in parts:
        if isinstance(p, tuple):
            kind, s = p
            dy = -drop_pt if kind == 'sub' else rise_pt
            art = ax.annotate(s, xy=(0.0, 0.0), xycoords=anchor,
                              xytext=(dx + 0.4, dy), textcoords='offset points',
                              fontsize=size, color=color, ha='left', va=va,
                              zorder=zorder, annotation_clip=False)
            dx += 0.4 + _text_w_pt(ax, s, size)
        else:
            art = ax.annotate(p, xy=(0.0, 0.0), xycoords=anchor,
                              xytext=(dx, 0.0), textcoords='offset points',
                              fontsize=size, color=color, ha='left', va=va,
                              zorder=zorder, annotation_clip=False)
            dx += _text_w_pt(ax, p, size)
        arts.append(art)
    return arts, width


def chain_frame(f, xy, parts, *, size=PT_BASE, color=None, ha='left',
                va='center', zorder=6):
    """``chain_data`` on a schematic Frame (axes fractions)."""
    return chain_data(f.ax, xy, parts, size=size, color=color, ha=ha, va=va,
                      zorder=zorder)


def sci_parts(value, digits=1):
    """['5.7', ' × 10', ('sup', '−4')] for 5.666e-4."""
    exponent = int(math.floor(math.log10(abs(value))))
    mantissa = value / 10.0 ** exponent
    text = f'{mantissa:.{digits}f}'
    if text in ('1.0', '1'):
        return ['10', ('sup', true_minus(exponent))]
    return [text, ' × 10', ('sup', true_minus(exponent))]


def plain_log_ticks(ax, ticks=LOG_TICKS, pad_pt=3.0):
    """Log ticks printed as ``10`` with a raised exponent, both at 7.0 pt.

    The tick label itself stays a real tick label (so ``NativeCanvas`` still
    measures the left reserve from the axis) and the exponent is annotated
    into the extra pad the tick label leaves.
    """
    ax.set_yscale('log')
    ax.yaxis.set_major_locator(FixedLocator(list(ticks)))
    ax.set_yticks(list(ticks))
    exps = [true_minus(int(round(math.log10(t)))) for t in ticks]
    widest = max(_text_w_pt(ax, e, PT_BASE) for e in exps)
    ax.set_yticklabels(['10'] * len(ticks))
    ax.tick_params(axis='y', pad=pad_pt + widest)
    ax.yaxis.set_minor_locator(NullLocator())
    ax.yaxis.set_minor_formatter(NullFormatter())
    # the exponent is anchored to the RIGHT EDGE of its own '10', not to the
    # spine: pinning it to the spine leaves a gap as wide as the difference
    # between this exponent and the widest one, which prints '10  0' instead
    # of a raised exponent.
    for label, exp in zip(ax.get_yticklabels(), exps):
        ax.annotate(exp, xy=(1.0, 0.42), xycoords=label, xytext=(0.4, 2.2),
                    textcoords='offset points', fontsize=PT_BASE,
                    color=COLORS['ink'], ha='left', va='center',
                    annotation_clip=False)
    return ax


def window_rule(ax, x=PRIMARY['budget'], *, top=REF_TOP, pad_pt=1.4):
    """The dotted window reference, drawn LAST and stepped around the text.

    ``reference_line`` draws one segment, so a full-height rule strikes
    through every direct label and note that spans its x (HEAD and v1 struck
    four lines in each of C and D).  The rule stops at ``top`` -- just above
    the highest trace -- and every text span it would cross is subtracted
    from it, so the reader still reads one dotted rule and no crossed type.
    """
    fig = ax.get_figure()
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    k = 72.0 / fig.dpi
    x_disp = ax.transData.transform((x, 1.0))[0]
    y_lo = ax.transData.transform((x, LOG_YLIM[0]))[1]
    y_hi = ax.transData.transform((x, top))[1]
    gaps = []
    for art in list(ax.texts) + [t for leg in ax.get_legend() and
                                 [ax.get_legend()] or [] for t in leg.get_texts()]:
        try:
            bb = art.get_window_extent(renderer)
        except Exception:
            continue
        if bb.x0 - pad_pt / k > x_disp or bb.x1 + pad_pt / k < x_disp:
            continue
        if bb.y1 < y_lo or bb.y0 > y_hi:
            continue
        gaps.append((bb.y0 - pad_pt / k, bb.y1 + pad_pt / k))
    gaps.sort()
    segments, cursor = [], y_lo
    for lo, hi in gaps:
        if lo > cursor:
            segments.append((cursor, min(lo, y_hi)))
        cursor = max(cursor, hi)
    if cursor < y_hi:
        segments.append((cursor, y_hi))
    inv = ax.transData.inverted()
    for lo, hi in segments:
        if hi - lo <= 1.0:
            continue
        y0 = inv.transform((x_disp, lo))[1]
        y1 = inv.transform((x_disp, hi))[1]
        line, = ax.plot([x, x], [y0, y1], color=MUTE, lw=LW_REF, zorder=1,
                        solid_capstyle='butt')
        line.set_dashes((2.2, 1.8))
    return segments


def axis_break(ax, x, *, size_pt=4.0):
    """Two hairline slashes on the x spine where the linear part joins the log.

    QA 2026-09-09: the first version converted ``x`` to an axes fraction and
    then drew it through ``get_xaxis_transform`` (which takes DATA x), so on
    the symlog axis both slashes collapsed onto the origin.  The slashes are
    now placed in data x, with their point offsets converted through
    ``transData`` at the spine.
    """
    trans = ax.get_xaxis_transform()
    fig = ax.get_figure()
    k = 72.0 / fig.dpi
    y_ref = ax.transData.transform((x, LOG_YLIM[0]))[1]
    x_disp = ax.transData.transform((x, LOG_YLIM[0]))[0]
    inv = ax.transData.inverted()

    def xd(off_pt):
        return inv.transform((x_disp + off_pt / k, y_ref))[0]

    h = 0.6 * size_pt / axes_h_pt(ax)
    for dx in (-0.30 * size_pt, 0.30 * size_pt):
        ax.plot([xd(dx - 0.35 * size_pt), xd(dx + 0.35 * size_pt)], [-h, h],
                transform=trans, color=COLORS['edge'], lw=LW_HAIR,
                clip_on=False, zorder=6, solid_capstyle='butt')
    return x


def badge_at(ax, xy, kind, *, xycoords, offset_pt, ha, va):
    """``Frame.badge`` styling on a data axes (a Frame would hide the axes)."""
    key, face, edge = BADGE_STYLE[kind]
    colour = label_color(COLORS[key], background=face)
    return ax.annotate(kind, xy=xy, xycoords=xycoords, xytext=offset_pt,
                       textcoords='offset points', fontsize=PT_BASE,
                       color=colour, ha=ha, va=va, zorder=7,
                       annotation_clip=False,
                       bbox=dict(boxstyle=f'round,pad=0.28,rounding_size={2.0 / PT_BASE:.3f}',
                                 facecolor=face, edgecolor=edge,
                                 linewidth=LW_HAIR))


def open_head(f, p0, p1, color):
    """The library's LW_EDGE '-|>' arrowhead, white-faced: credit gated to 0."""
    arr = FancyArrowPatch(
        p0, p1, arrowstyle='-|>,head_length=3.20,head_width=1.92',
        mutation_scale=1.0, facecolor='white', edgecolor=color,
        linewidth=f.lw(LW_EDGE), shrinkA=0, shrinkB=0, capstyle='round',
        zorder=4.6)
    f.ax.add_patch(arr)
    return arr


def subtree_delivery(f, nodes, targets, cname, rule_color):
    """``credit_delivery(mode='subtree')`` with the capsule hue named here."""
    for t in targets:
        f._capsule(nodes, t, cname)
        par = nodes.parent.get(t)
        if par is not None:
            p0 = nodes[par] if par in nodes else nodes.soma
            # QA 2026-09-09: at the 34 pt card scale the 0.40-0.80 span was
            # a head with no shaft; the arrow now runs most of the segment
            f.arrow(_lerp(p0, nodes[t], 0.16), _lerp(p0, nodes[t], 0.84),
                    color=COLORS[rule_color], lw=LW_EDGE, head=3.4, zorder=4.6)


def distal_oracle_delivery(f, nodes):
    """Mark the two weighted distal supports, excluding both proximal sites.

    Equal site dots identify recipients, not profile weights; the adjacent
    multiplier key explicitly retains the fixed nonuniform profiles p1/p2.
    The terminal-only collars must not imply oracle credit at the junctions.
    """
    groups = [nodes.terminals_under(root) for root in ('JL', 'JR')]
    for group in groups:
        f._draw_chains([[nodes[t] for t in group]], mix('oracle', 16), 3.2)
        for t in group:
            f.disc(nodes[t], 1.2, fill=COLORS['oracle'], edge='none', zorder=4.6)
    return groups


def axes_w_pt(ax):
    return ax.get_position().width * ax.get_figure().get_figwidth() * 72.0


def axes_h_pt(ax):
    return ax.get_position().height * ax.get_figure().get_figheight() * 72.0


def min_separation_pt(fig, group_a, group_b):
    """Smallest gap in points between two artist groups (negative = overlap)."""
    renderer = fig.canvas.get_renderer()
    k = 72.0 / fig.dpi
    worst = float('inf')
    for a in group_a:
        ba = a.get_window_extent(renderer)
        for b in group_b:
            bb = b.get_window_extent(renderer)
            gap = max(max(ba.x0 - bb.x1, bb.x0 - ba.x1),
                      max(ba.y0 - bb.y1, bb.y0 - ba.y1))
            worst = min(worst, gap * k)
    return worst


def wrap_lines(ax, text, max_w_pt, max_lines=2):
    """The plan's 'wrap to two lines if it exceeds the axes width' rule.

    Greedy and measured, never abbreviated: ``_wrap_to_width`` delegates to
    ``textwrap`` whose ' [...]' placeholder passes its own word-count guard,
    so a two-line fallback there can silently drop the end of a sentence.
    """
    if _text_w_pt(ax, text, PT_BASE) <= max_w_pt:
        return [text]
    words, lines, cur = text.split(), [], ''
    for word in words:
        trial = word if not cur else f'{cur} {word}'
        if cur and _text_w_pt(ax, trial, PT_BASE) > max_w_pt:
            lines.append(cur)
            cur = word
        else:
            cur = trial
    if cur:
        lines.append(cur)
    return lines


def stack(ax, x_frac, y_frac, lines, *, ha='left', color=None, lead_pt=9.0,
          zorder=6):
    """Stack 7.0-pt lines downward from an axes-fraction anchor."""
    color = MUTE if color is None else color
    arts = []
    for i, line in enumerate(lines):
        if isinstance(line, list):
            a, _ = chain_data(ax, (x_frac, y_frac), line, color=color, ha=ha,
                              va='center', transform=ax.transAxes,
                              zorder=zorder)
            arts += a
        else:
            arts.append(ax.text(x_frac, y_frac, line, transform=ax.transAxes,
                                fontsize=PT_BASE, color=color, ha=ha,
                                va='center', zorder=zorder, clip_on=False))
        y_frac -= lead_pt / axes_h_pt(ax)
    return arts, y_frac


def seeds_and_mean(ax, x, values, mean, lo, hi, color, *, marker='D', fan=.09,
                   seeds=True, mfc=None, mec=None, mew=None):
    values = np.asarray(values, float)
    if seeds and len(values):
        ax.plot(x + np.linspace(-fan, fan, len(values)), values, ls='none',
                marker='o', ms=SEED_MS, mfc=color, mec='none',
                alpha=SEED_ALPHA, zorder=2)
    ax.errorbar(x, mean, yerr=None if lo is None else [[mean - lo], [hi - mean]],
                fmt=marker, color=color, ms=MARKER_MS,
                mfc=color if mfc is None else mfc,
                mec='white' if mec is None else mec,
                mew=LW_HAIR if mew is None else mew,
                elinewidth=LW_ERR, capsize=2, zorder=4)


# ── data ------------------------------------------------------------------
def nominal_teacher(opposed):
    """model.teacher's own gains with the log-normal perturbation set to zero."""
    class Silent:
        def normal(self, loc, scale, size):
            return np.zeros(size)
    with mock.patch.object(model.np.random, 'default_rng',
                           lambda *a, **k: Silent()):
        return model.teacher(0, opposed)


def teacher_tuning():
    """Nominal terminal voltage against the latent feature, via model.forward."""
    z = np.linspace(-2.0, 2.0, 201)
    xx = np.tile(np.column_stack([z, z]), (1, 2))
    x = np.column_stack([np.exp(xx), np.exp(-xx), np.zeros((len(z), 2))])
    aligned = model.forward(nominal_teacher(False)[None], x)['voltage'][0]
    opposed = model.forward(nominal_teacher(True)[None], x)['voltage'][0]
    inc, dec = aligned[:, 0], opposed[:, 2]
    assert np.allclose(aligned[:, 2], inc) and np.allclose(opposed[:, 0], inc)
    xp, xm = np.exp(z), np.exp(-z)
    assert np.allclose(inc, (8 * xp + .25 * xm) / (1 + 8 * xp + .25 * xm + .25 * xp + 8 * xm))
    assert np.allclose(dec, (.25 * xp + 8 * xm) / (1 + .25 * xp + 8 * xm + 8 * xp + .25 * xm))
    assert np.all(np.diff(inc) > 0) and np.all(np.diff(dec) < 0)
    table = pd.DataFrame(dict(z=z, v_increasing=inc, v_decreasing=dec))
    table.to_csv(FIG / 'teacher_tuning_source.csv', index=False)
    return table


def load_tables():
    read = lambda p: pd.read_csv(p, float_precision='round_trip')  # noqa: E731
    t = dict(band=read(FIG / 'curve_band_source.csv'),
             curves=read(OUT / 'summaries/all_curves.csv'),
             means=read(OUT / 'summaries/condition_means.csv'),
             endpoints=read(OUT / 'summaries/all_endpoints.csv'),
             contrasts=read(OUT / 'summaries/paired_contrasts.csv'),
             seed_contrasts=read(OUT / 'summaries/paired_seed_contrasts.csv'),
             historical=read(FIG / 'historical_cancellation_source.csv'),
             audit=json.loads((OUT / 'summaries/completeness_audit.json').read_text()),
             upstream=read(J / 'source_data/conductance_credit_demand/opponent'
                           / 'summaries/context_gradient_summary.csv'))
    ep = t['endpoints']
    for task in ('aligned_strong', 'opposed_strong'):
        for rule in CURVE_RULES:
            b = t['band'][(t['band'].task == task) & (t['band'].rule == rule)
                          & (t['band'].rate == PRIMARY['rate'])]
            assert len(b) == 12 and b.step.min() == 0 and b.step.max() == 16384
            assert not (b['mean'] < b.ci_low).any()
            assert not (b['mean'] > b.ci_high).any()
    for rule in RULES:
        if rule == 'calibrated_broadcast':
            continue
        f = ep[(ep.task == 'opposed_strong') & (ep.rate == PRIMARY['rate'])
               & (ep.budget == PRIMARY['budget']) & (ep.rule == rule)]
        m = t['means'][(t['means'].task == 'opposed_strong')
                       & (t['means'].rate == PRIMARY['rate'])
                       & (t['means'].budget == PRIMARY['budget'])
                       & (t['means'].rule == rule)]
        assert len(f) == 20 and f.seed.nunique() == 20 and len(m) == 1
        assert int(m.iloc[0].n) == 20
        assert abs(f.test_nmse.mean() - m.iloc[0]['mean']) < 1e-12
    return t


def cond(t, task, rule, budget=PRIMARY['budget'], rate=PRIMARY['rate']):
    m = t['means']
    return m[(m.task == task) & (m.rate == rate) & (m.budget == budget)
             & (m.rule == rule)].iloc[0]


# ── A: the circuit, the context gate and the nominal teacher ──────────────
FOOTER_A = ('exp(±z) inputs at every terminal; 24 plastic conductances; '
            'context redrawn each example')
PERTURB_A = ('nominal teacher; every fitted teacher is independently '
             'perturbed')


def panel_task(ax, tuning):
    f = Frame(ax)
    core = f.task_card((0.0, 0.0, 1.0, 1.0), footer=FOOTER_A)
    x0, y0, w, h = core
    w_pt, h_pt = w * f.w_pt, h * f.h_pt
    right_w = 66.0                      # the inset column, at the card's right
    tree_rect = (x0 + f.fx(4.0), y0 + f.fy(8.0), f.fx(w_pt - right_w - 10.0),
                 h - f.fy(28.0))
    # QA 2026-09-09: mode='plain' (no library input dot at the terminals), so
    # each terminal carries exactly one E and one I contact
    nodes = f.balanced_tree(tree_rect, depth=2, trunk=False, mode='plain',
                            output='', soma_r_pt=3.0)
    sx, sy = nodes.soma
    # excitatory AND inhibitory drive on every terminal branch: the input
    # symmetry is what makes the task hard, and HEAD drew no inputs at all
    for t in nodes.terminals:
        par = nodes[nodes.parent[t]]
        f.contact(_lerp(par, nodes[t], 0.60), kind='exc', active=True,
                  dia_pt=CONTACT_DIA_PT)
        f.contact(_lerp(par, nodes[t], 0.80), kind='inh', active=True,
                  dia_pt=CONTACT_DIA_PT)
    f.gate(nodes['JL'], closed=False, badge='c', nodes=nodes, node='JL')
    f.gate(nodes['JR'], closed=True, descendants=['JR'], badge='c',
           nodes=nodes, node='JR')
    # exactly one delivery glyph: the local distal gate's own address
    f.credit_delivery(nodes, mode='subtree', targets=['JL'],
                      rule_color='shunting')
    f.note('address_tint',
           reason='the addressed subtree is the local rule’s own target; '
                  'its tint is the rule colour at 16 %')
    # QA 2026-09-10: the mute output arrow, drawn exactly as the four B cards
    # draw it (mode='forward' would add the library's own terminal contacts on
    # top of the hand-placed exc/inh pairs).  Without it 'V_s' hung off the
    # black delta-0 arrow, and A was the only tree in the figure with no output.
    f.arrow((sx + f.fx(nodes.soma_r_pt + 1.5), sy),
            (sx + f.fx(nodes.soma_r_pt + 1.5 + 11.0), sy),
            color=MUTE, lw=LW_EDGE, head=3.4, zorder=4.5)
    f.subscript((sx + f.fx(nodes.soma_r_pt + 1.5 + 11.0 + 2.5), sy), 'V', 's',
                ha='left')
    f.error_in(nodes.soma, label='δ0', side='right')
    gate = COLORS['gate']
    jl, jr = nodes['JL'], nodes['JR']
    f.subscript(f._off(jl, -4.6, -12.0), 'a', 'p', ' = 0', color=gate,
                ha='right', va='top')
    col_x = x0 + w - f.fx(right_w + 3.0)
    rect = (col_x, y0 + f.fy(46.0), f.fx(right_w), f.fy(32.0))
    n0 = len(ax.texts)
    # anchored from the inset column, not from J2: run east from J2 and the
    # tag crosses the inset's y spine, a collision no audit can see
    f.subscript((col_x - f.fx(4.0), jr[1] - f.fy(13.0)), 'a', 'p', ' = 10',
                color=gate, ha='right', va='top')
    gate_tag = list(ax.texts[n0:])
    lift = CONTACT_DIA_PT * 0.5 + 3.0
    for t, sub in zip(nodes.terminals, ('1', '2', '1', '2')):
        f.subscript((nodes[t][0], nodes[t][1] + f.fy(lift)), 'z', sub,
                    size=PT_BASE, ha='center', va='bottom')
    top = max(nodes[t][1] for t in nodes.terminals)
    # the right-hand tag is clamped off the inset's own tick labels, which
    # hang 8 pt left of the inset frame
    limit = col_x - f.fx(15.0)
    for root, tag in (('JL', 'subtree 1'), ('JR', 'subtree 2')):
        terms = nodes.terminals_under(root)
        cx = float(np.mean([nodes[u][0] for u in terms]))
        half = f.fx(_text_w_pt(ax, tag, PT_BASE) / 2.0)
        cx = min(cx, limit - half)
        f.text((cx, top + f.fy(lift + 10.0)), tag, size=PT_BASE, va='bottom')
    # nominal teacher inset
    inner = f.axes_inset(rect)
    inner.plot(tuning.z, tuning.v_increasing, color=INK, lw=LW_REF, zorder=3)
    dec, = inner.plot(tuning.z, tuning.v_decreasing, color=INK, lw=LW_REF,
                      zorder=3)
    dec.set_dashes(DASH[1])
    inner.set_xlim(-2.0, 2.0)
    inner.set_ylim(0.0, 1.0)
    inner.set_xticks([])
    inner.set_yticks([0, 1], ['0', '1'])
    inner.tick_params(labelsize=PT_BASE, pad=1.5)
    inner.text(0.0, 0.04, 'z', fontsize=PT_BASE, color=INK, ha='center',
               va='bottom')
    f.text((col_x, y0 + f.fy(83.5)), 'teacher V', size=PT_BASE, ha='left',
           va='center')
    # QA 2026-09-09 (2): the two line samples are deleted -- Fig 5 carries
    # exactly one key (panel C; PLAN section 4 C, AMENDMENTS CF-5) -- and each
    # teacher curve is named by its own direct label.  'both subtrees' is
    # 40 pt of a 66 pt inset whose two logistics sweep its full height, so the
    # label cannot be set between the curves; it is set in the free band under
    # the inset, on its curve's own side, and tied to the curve it names by a
    # hairline leader that ends 1.6 pt short of the trace.
    for dashed, lines, ha in (
            (False, ('aligned:', 'both', 'subtrees'), 'left'),
            (True, ('opposed:', 'subtree 2'), 'right')):
        series = tuning.v_decreasing if dashed else tuning.v_increasing
        # the leader touches its own curve at V = 0.28: the two contact points
        # are then 16 pt apart, 6 pt of each leader falls inside the inset,
        # and nothing lies between a label and the trace it names
        v_at = 0.28
        z_at = float(np.interp(v_at, series[::-1] if dashed else series,
                               tuning.z[::-1] if dashed else tuning.z))
        # through the inset's OWN transform: axes_inset reserves its tick
        # band inside ``rect``, so the rect corners are not the data corners
        lx, ly = ax.transData.inverted().transform(
            inner.transData.transform((z_at, v_at)))
        anchor = col_x if ha == 'left' else col_x + rect[2]
        y = y0 + f.fy(30.0)
        for line in lines:
            f.text((anchor, y), line, size=PT_BASE, ha=ha)
            y -= f.fy(8.5)
        # the leader is set one third in from the inset's own spine, so it
        # reads as a leader to its curve and not as a second axis rule
        ax.plot([lx, lx], [y0 + f.fy(33.6), ly - f.fy(1.8)],
                color=MUTE, lw=LW_HAIR, zorder=2, solid_capstyle='butt')
    perturbation = f.room(core, 30.0) and (
        _text_w_pt(ax, PERTURB_A, PT_BASE) <= w_pt - 6.0)
    if perturbation:
        f.text((x0 + w / 2.0, y0 + f.fy(2.5)), PERTURB_A, size=PT_BASE,
               color=MUTE, va='bottom')
    f.require_soma_lowest()
    f.require_delta0()
    return dict(nodes=nodes, gate_tag=gate_tag, inset=inner,
                perturbation=bool(perturbation), core_pt=h_pt)


# ── B: the four deliveries of the somatic error ───────────────────────────
def card_tree(f, core, *, head_pt=3.0, foot_pt=10.0):
    """Ghost copy of A's tree with the closed gate at J2 and its own delta-0.

    ``foot_pt`` lifts the soma clear of the card's own bottom edge: the
    library's error_in tail sits (r + 7) pt below the soma, and task_card's
    core reaches the card edge, so a tree drawn on the floor of the core puts
    the delta-0 tag outside the card it belongs to.

    QA 2026-09-10: the rect is the plan's ``(f.fx(2), f.fx(46))`` again.  The
    46-pt width is not what sets the drawing: ``_fit_tree`` is aspect-true and
    on a 38-pt card core the tree is height-bound (measured s = 12.5 pt of
    tree height against 26 pt of free width at the old 34-pt rect), so the
    lever is the foot.  ``foot_pt`` 14 -> 10 is the smallest that keeps the
    delta-0 tag inside the card (tag centre lands 4.5 pt above the core floor,
    box floor 2.7 pt) and takes the tree from 18.0 x 12.5 pt to 23.7 x 16.5 pt,
    pitch 6.0 -> 7.9 pt, so the terminals and junction rings read at print
    scale.  The canopy top is unchanged at (core_h - head_pt - 4) pt, so the
    broadcast card's bus rail does not move.
    """
    x0, y0, w, h = core
    rect = (x0 + f.fx(2.0), y0 + f.fy(foot_pt), f.fx(46.0),
            h - f.fy(foot_pt + head_pt))
    nodes = f.balanced_tree(rect, depth=2, trunk=False, mode='plain',
                            ghost=True)
    # the double ring alone marks the closed gate: a 'c' badge lands on the
    # exact card's alpha tag at this pitch
    # QA 2026-09-09: no descendant fade on the 34 pt cards (a 38 % hairline
    # subtree vanished at print scale); the closed ring and the open head
    # mark the suppression.
    f.gate(nodes['JR'], closed=True, descendants=None, nodes=nodes,
           node='JR', badge=None)
    sx, sy = nodes.soma
    x1 = sx + f.fx(nodes.soma_r_pt + 1.5)
    f.arrow((x1, sy), (x1 + f.fx(7.0), sy), color=MUTE, lw=LW_EDGE, head=3.4,
            zorder=4.5)
    # side='left': the key column starts 46 pt right of the card edge and the
    # right-hand tag would sit on its first line
    f.error_in(nodes.soma, side='left')
    return nodes


def key_lines(f, core, key_x_pt, lines, *, lead_pt=10.0):
    """The card's multiplier lines: 10-pt leading, three keys, wrapped."""
    x0, y0, w, h = core
    x = x0 + f.fx(key_x_pt)
    y = y0 + h - f.fy(5.0)
    for parts, color in lines:
        chain_frame(f, (x, y), parts, size=PT_BASE, color=color, ha='left',
                    va='center')
        y -= f.fy(lead_pt)
    return y


def panel_deliveries(ax):
    f = Frame(ax)
    gap_x, gap_y = f.fx(8.0), f.fy(5.0)
    cw, ch = (1.0 - gap_x) / 2.0, (1.0 - gap_y) / 2.0
    cells = {'hero': (0.0, ch + gap_y, cw, ch),
             'exact': (cw + gap_x, ch + gap_y, cw, ch),
             'broadcast': (0.0, 0.0, cw, ch),
             'oracle': (cw + gap_x, 0.0, cw, ch)}
    key_x = 50.0
    shunting, gate = COLORS['shunting'], COLORS['gate']

    cell = cells['hero']
    core = f.task_card(cell, title='Local distal gate', emphasis=True)
    f.badge((cell[0] + cell[2] - f.fx(4.0), cell[1] + cell[3] - f.fy(3.5)),
            'local rule')
    nodes = card_tree(f, core)
    subtree_delivery(f, nodes, ['JL'], 'shunting', 'shunting')
    # AMENDMENTS B10: the caption's Gamma sentence needs an on-artwork referent
    f.text((core[0] + f.fx(key_x - 5.0), core[1] + core[3] - f.fy(5.0)), 'Γ',
           size=PT_BASE, color=COLORS['gate'], ha='right', va='center')
    open_head(f, _lerp(nodes.soma, nodes['JR'], 0.16),
              _lerp(nodes.soma, nodes['JR'], 0.84), shunting)
    key_lines(f, core, key_x, [
        (['distal × 1[', 'a', ('sub', 'p'), ' = 0]'], INK),
        (['proximal, soma × 1'], INK),
        (['context + local'], MUTE),
        (['eligibility only'], MUTE)])

    cell = cells['exact']
    core = f.task_card(cell, title='Exact path')
    f.badge((cell[0] + cell[2] - f.fx(4.0), cell[1] + cell[3] - f.fy(3.5)),
            'exact')
    nodes = card_tree(f, core)
    # one chain per subtree into the two inner terminals: chains into all four
    # would repaint the whole arbor and lose the ghost comparison geometry.
    f.credit_delivery(nodes, mode='exact', targets=['T2', 'T3'],
                      alpha_tags=True)
    # QA 2026-09-09 (2): the hand-set alpha-2 tag is restored, on the DISTAL
    # segment of the route (mid JL->T2) rather than above the terminal, where
    # it ran into the card title.  The junction factor is set by hand as
    # well: credit_delivery drops its own
    # alpha tags below ALPHA_TAG_MIN_PITCH_PT, and this card's terminal pitch
    # is 6.8 pt, so without this the key line 'proximal x a1' has no referent
    # QA 2026-09-09 (2): the junction factor is set beside the PROXIMAL
    # segment it multiplies (mid soma->JL) rather than at JL itself: the
    # JL->T2 route is only 7.6 pt long, so two tags anchored at its two ends
    # share a line, and the proximal midpoint drops this one 7.2 pt clear.
    _p1 = _lerp(nodes.soma, nodes['JL'], 0.5)
    f.subscript((_p1[0] - f.fx(2.6), _p1[1]), 'α', '1', size=PT_BASE,
                color=COLORS['bp'], ha='right', va='center')
    # the distal factor, set by hand: the library tags only the junction
    # factor on a depth-2 route.  This card's whole tree is 23.2 x 12.5 pt and
    # the JL->T2 route is 4.3 pt long, so the two 8.3 x 10.1 pt tags cannot
    # both sit beside it: alpha_1 takes the proximal segment (above) and
    # alpha_2 is set over its own terminal, 3.7 pt above T2 -- 2.4 pt under
    # the card title and 2.1 pt over alpha_1's box.
    # QA 2026-09-10: 4.8 pt, not 3.7 -- the tag is set va='center', so at 3.7
    # its descender box sat on the 1.6-pt terminal disc (JUNCTION_R_PT + the
    # glyph's 2.5-pt half-height + 0.7 pt of air = 4.8), and T2 is the canopy
    # top, whose height does not move with the foot.
    f.subscript((nodes['T2'][0], nodes['T2'][1] + f.fy(4.8)), 'α', '2',
                size=PT_BASE, color=COLORS['bp'], ha='center', va='center')
    key_lines(f, core, key_x, [
        (['distal × ', 'α', ('sub', '1'), 'α', ('sub', '2')], INK),
        (['proximal × ', 'α', ('sub', '1')], INK),
        (['context sets ', 'α', ('sub', '2')], MUTE)])

    cell = cells['broadcast']
    core = f.task_card(cell, title='Unit broadcast')
    nodes = card_tree(f, core)
    bus_targets = nodes.terminals + ['JL', 'JR']
    seen = set(map(id, ax.patches))
    f.credit_delivery(nodes, mode='neuron', targets=bus_targets)
    # QA 2026-09-10: the library ends every drop 2.8 pt short of its site.  On
    # the two junctions that standoff is right (the gate ring is 3.4 pt across,
    # so a longer drop would spear it), but on a bare terminal it reads as a bus
    # hovering over the canopy rather than delivering into it.  The glyph stays
    # the library's (rail, riser, source dot, heads); only the four terminal
    # tips are carried 1.6 pt further down, to the same 1.2-pt standoff the
    # subtree arrows on cards 1 and 4 keep from their roots.
    drops = [a for a in ax.patches
             if id(a) not in seen and isinstance(a, FancyArrowPatch)]
    for target, art in zip(bus_targets, drops):
        if target not in nodes.terminals:
            continue
        (ax0, ay0), (ax1, ay1) = art._posA_posB
        art.set_positions((ax0, ay0), (ax1, ay1 - f.fy(1.6)))
    key_lines(f, core, key_x, [
        (['all six sites × 1'], INK),
        (['soma × 1'], INK),
        (['one scalar,'], MUTE),
        (['no address'], MUTE)])

    cell = cells['oracle']
    core = f.task_card(cell, title='Two-profile oracle')
    f.badge((cell[0] + cell[2] - f.fx(4.0), cell[1] + cell[3] - f.fy(3.5)),
            'oracle')
    nodes = card_tree(f, core)
    distal_oracle_delivery(f, nodes)
    key_lines(f, core, key_x, [
        (['distal 1 × p', ('sub', '1'), 'ĉ', ('sub', '1')], INK),
        (['distal 2 × p', ('sub', '2'), 'ĉ', ('sub', '2')], INK),
        (['proximal, soma × 1'], INK),
        (['fixed p; oracle ĉ'], MUTE)], lead_pt=9.0)
    f.require_soma_lowest()
    f.require_delta0()
    del gate


# ── C / D: learning curves ────────────────────────────────────────────────
def y_frac(value):
    lo, hi = LOG_YLIM
    return (math.log10(value) - math.log10(lo)) / (math.log10(hi) - math.log10(lo))


def x_frac(ax, x):
    return ax.transAxes.inverted().transform(ax.transData.transform((x, 1.0)))[0]


def x_data(ax, frac):
    """Axes fraction -> data x (box-independent: the box transforms cancel)."""
    return ax.transData.inverted().transform(ax.transAxes.transform((frac, 0.0)))[0]


def y_data(frac, ylim=None):
    """Axes fraction -> data y on the shared log ladder."""
    lo, hi = LOG_YLIM if ylim is None else ylim
    return 10.0 ** (math.log10(lo) + frac * (math.log10(hi) - math.log10(lo)))


def curves(ax, t, task, *, legend=False):
    band = t['band']
    for rule in sorted(CURVE_RULES, key=lambda r: CURVE_Z[r]):
        b = band[(band.task == task) & (band.rule == rule)
                 & (band.rate == PRIMARY['rate'])].sort_values('step')
        color = rc(rule)
        ax.fill_between(b.step, b.ci_low, b.ci_high, color=color, alpha=.14,
                        lw=0, zorder=1)
        line, = ax.plot(b.step, b['mean'], color=color, lw=LW_DATA,
                        zorder=CURVE_Z[rule], label=RULES[rule][0])
        if rule in CURVE_DASH:
            line.set_dashes(CURVE_DASH[rule])
    ax.set_xscale('symlog', linthresh=64)
    ax.set_xlim(0, 16384)
    ax.set_xticks([0, 64, 1024, 16384], ['0', '64', '1,024', '16,384'])
    ax.xaxis.set_minor_locator(NullLocator())
    ax.set_yscale('log')
    ax.set_ylim(*LOG_YLIM)
    ax.set_xlabel('Updates')
    ax.xaxis.labelpad = 2.5
    style_panel(ax)
    plain_log_ticks(ax)          # after style_panel: it resets the tick pad
    ax.tick_params(axis='x', pad=2.0)
    ax.get_xticklabels()[-1].set_ha('right')
    # QA 2026-09-10 (visual review): D labels its own ladder.  It used to
    # borrow C's, but the panels are separately lettered and 38 pt apart --
    # wider than C's own tick pitch -- so nothing marked the scale as shared
    # and D's letter floated in an empty 38 pt gutter.  The left reserve is
    # declared for every data panel alike, so the labels cost no width.
    ax.set_ylabel('Held-out NMSE')
    if legend:
        handles = [Line2D([], [], color=rc(r), lw=LW_DATA, label=RULES[r][0],
                          dashes=CURVE_DASH.get(r, (1e6, 1.0)))
                   for r in CURVE_RULES]
        # two columns in the band above 10^0.  The plan asks for the lower
        # left; measured on this ladder the lower left is where the trio's
        # own direct label sits (y frac 0.24) and a four-row key needs 40 pt
        # of the 30 pt below it, so the key takes the band no trace enters.
        leg = ax.legend(handles=handles, loc='upper left', frameon=False,
                        fontsize=PT_BASE, handlelength=1.4, handletextpad=.5,
                        labelspacing=.18, columnspacing=1.1, ncol=2,
                        borderaxespad=.2)
        ax._oracle_entry = leg.get_texts()[
            CURVE_RULES.index('ancestry_two_leaf_oracle_unit_proximal')]
    return ax


def curve_annotations(ax, t, task):
    """Direct labels, the statistics tag and (D) the bound-contact mark."""
    band = t['band']
    at = lambda rule, step: float(band[(band.task == task)  # noqa: E731
                                       & (band.rule == rule)
                                       & (band.step == step)]['mean'].iloc[0])
    broadcast = at('unit_broadcast', 4096)
    trio = [at(r, 4096) for r in CURVE_RULES if r != 'unit_broadcast']
    printed = dict(broadcast=broadcast, trio=trio,
                   trio_mean=float(np.mean(trio)))
    aligned = task == 'aligned_strong'
    if aligned:
        assert abs(broadcast - 5.666e-4) < 5e-6, broadcast
        assert max(trio) < 1.1e-5, trio
    else:
        assert abs(broadcast - 0.52191) < 5e-4, broadcast
        assert max(trio) < 3e-5, trio
    # the amber curve's own label, hung clear of its band
    amber_parts = ['unit broadcast '] + (sci_parts(broadcast)
                                         if aligned else [f'{broadcast:.2f}'])
    # QA 2026-09-10 (visual review): the label hangs within half a decade of
    # its own trace now that the head is a decade lower, and in D it stops at
    # 0.55 of the width -- right of that the bound-contact tick hangs off the
    # broadcast curve at this height and would strike the text.
    chain_data(ax, (0.98, y_frac(4.0e-2) if aligned else 0.86), amber_parts,
               color=AMBER_TEXT, ha='right', transform=ax.transAxes)
    # the three coincident rules, named once, with a hairline leader that
    # stops short of the trio's own band
    trio_parts = ['exact, gate, oracle ≈ '] + sci_parts(
        printed['trio_mean'], digits=0)
    _, trio_w = chain_data(ax, (0.02, y_frac(6.0e-5)), trio_parts, color=INK,
                           ha='left', transform=ax.transAxes)
    band_low = band[(band.task == task) & (band.rule != 'unit_broadcast')
                    ].groupby('step').ci_low.min()
    # QA 2026-09-10 (visual review): the leader ends under the bundle AT THE
    # 4,096 checkpoint, which is the step the printed value belongs to.  It
    # used to stop at 1,024, an order of magnitude above that value, and read
    # as a fifth trace hanging in clear space.
    x_lead = float(PRIMARY['budget'])
    y_lead = float(np.interp(x_lead, band_low.index, band_low.values)) * 0.75
    x_start = 0.02 + (trio_w + 6.0) / axes_w_pt(ax)
    ax.plot([x_data(ax, x_start), x_lead],
            [y_data(y_frac(6.0e-5) - 0.018), y_lead],
            color=MUTE, lw=LW_HAIR, zorder=2)
    # the window reference is named at the top of its own dotted rule.  The
    # rule stops at REF_TOP, just above the highest trace, so it cannot strike
    # through the text band above it (HEAD's and v1's dotted rule ran the full
    # height and crossed four lines of type in each of C and D).
    # QA 2026-09-09: anchored to the TOP OF THE RULE (REF_TOP, data y), not to
    # the axes top, so the tag sits on the rule it names rather than in the
    # title band 35-40 pt above it.
    # The tag sits beside the rule at NMSE 1e-2, the band both panels leave
    # empty between the broadcast trace above and the trio below; the
    # axes-top and rule-top placements collided with the stats line.
    # QA 2026-09-09 (2): C and D now set the tag identically -- right of the
    # rule at NMSE 1e-2, ha='left' -- so the C/D symmetry the plan asks for
    # holds; D's bound-contact tag is moved down out of that band below.
    # both panels set it at the TOP OF THE RULE (REF_TOP, where window_rule
    # stops), ha='left' -- the C/D symmetry the plan asks for, and the only
    # height in D that is clear of both the broadcast trace and the
    # conductance-bound tag.
    ax.annotate('4,096', xy=(PRIMARY['budget'], REF_TOP), xycoords='data',
                xytext=(2.0, 0.0),
                textcoords='offset points', fontsize=PT_BASE, color=MUTE,
                ha='left', va='center',
                zorder=6, annotation_clip=False)
    w = axes_w_pt(ax) - 4.0
    if aligned:
        # QA 2026-09-10 (visual review): 'Adam 0.03 . n = 20 seeds' and
        # 'mean +- 95 % pointwise seed bootstrap' are the caption's own words
        # ('means of 20 paired simulation seeds at Adam 0.03 with 95 %
        # pointwise whole-seed bootstrap bands'), so they leave the axes with
        # the decade of head that held them.  Only the interpolation caveat,
        # which the caption does not carry, stays on the panel, in the free
        # corner under the trio's own label.
        note = ['12 saved checkpoints;', 'segments are interpolation']
        printed['annotation_lines'] = list(note)
        stack(ax, 0.02, 0.155, note, ha='left', lead_pt=8.0)
    else:
        # the optimiser and n line goes with C's: it is the same caption
        # sentence, and so is 'fixed checkpoint at each saved step', which C
        # already carries as '12 saved checkpoints'.  What is left is the one
        # line that separates this panel's endpoint from E's and F's readout,
        # and the band it leaves under it is the broadcast label's.
        lines = ['validation-selected broadcast 0.49 (E, F)']
        printed['annotation_lines'] = lines
        stack(ax, TEXT_RIGHT, 0.950, lines, ha='right', lead_pt=8.5)
        printed.update(bound_contact(ax, t))
    printed['window_rule_segments'] = len(window_rule(ax))
    return printed


def bound_contact(ax, t):
    """D's bound-contact tick and tag, from all_curves.first_bound_step."""
    cur = t['curves']
    sel = cur[(cur.task == 'opposed_strong') & (cur.rule == 'unit_broadcast')
              & (cur.rate == PRIMARY['rate'])]
    first = sel.groupby('seed').first_bound_step.max()
    contacted = first[first > 0]
    by_4096 = int((contacted <= 4096).sum())
    by_16384 = int((contacted <= 16384).sum())
    assert len(first) == 20 and by_4096 == 18 and by_16384 == 20
    for rule in ('exact', 'hard_distal_unit_proximal',
                 'shunt_proportional_unit_proximal'):
        other = cur[(cur.task == 'opposed_strong') & (cur.rule == rule)
                    & (cur.rate == PRIMARY['rate'])]
        assert int((other.groupby('seed').first_bound_step.max() > 0).sum()) == 0
    median = float(np.median(contacted))
    step = round_half_up(median)
    assert step == 717, step
    band = t['band']
    amber = band[(band.task == 'opposed_strong')
                 & (band.rule == 'unit_broadcast')
                 & (band.rate == PRIMARY['rate'])].sort_values('step')
    y_here = float(np.interp(step, amber.step, amber['mean']))
    # mute, not amber: an amber tick on the amber curve is invisible, and the
    # tick is an annotation mark rather than a second broadcast series
    ax.plot([step, step], [y_here * 0.72, y_here * 1.42], color=MUTE,
            lw=LW_ERR, zorder=6, solid_capstyle='butt')
    # QA 2026-09-10 (visual review): the tick is named.  It used to be an
    # unlabelled black bar 18 pt left of the labelled '4,096' rule, which a
    # reader takes for part of that annotation; its value lived only in the
    # caption.  The tag now sits in the band the broadcast trace and the trio
    # leave open, with its top line 3 pt under the tick itself, so the old
    # hairline leader up to the tick is gone with it.
    lines = ['broadcast reaches a conductance',
             f'bound in {by_4096}/20 fits by 4,096;',
             f'tick: median {step}']
    # QA 2026-09-11 (regression check): the 3-pt premise did not hold -- on
    # the page the tag's top line sat 8 pt under the tick and 21 pt to its
    # right, with the labelled 4,096 rule between them as a competing
    # referent, so 'tick: median 717' had nothing on the page to point at.
    # The tag drops 3.7 pt (0.63 -> 0.60; the trio and its label stay two
    # decades below) and the mute hairline is back: it rises from the top
    # line, which spans the tick's x, to 2.2 pt under the tick's foot, the
    # same y_text < y_lead < datum rule as F's column ties.
    tag_top = 0.60
    stack(ax, 0.99, tag_top, lines, ha='right', lead_pt=8.5)
    tie_leader(ax, step, tag_top, y_here * 0.72)
    return dict(bound_median_step=step, bound_by_4096=by_4096,
                bound_by_16384=by_16384, bound_y=y_here)


# ── E: the task-by-rule interaction ───────────────────────────────────────
def interaction(ax, t):
    c, s = t['contrasts'], t['seed_contrasts']
    color = COLORS['shunting']
    printed, per_seed = {}, {}
    for i, budget in enumerate((4096, 16384)):
        key = ((s.task == 'opposed_minus_aligned') & (s.rate == PRIMARY['rate'])
               & (s.budget == budget) & (s.left == 'unit_broadcast')
               & (s.right == 'hard_distal_unit_proximal'))
        vals = s[key].sort_values('seed')
        m = c[(c.task == 'opposed_minus_aligned') & (c.rate == PRIMARY['rate'])
              & (c.budget == budget) & (c.left == 'unit_broadcast')
              & (c.right == 'hard_distal_unit_proximal')].iloc[0]
        assert len(vals) == 20
        assert abs(vals.difference.mean() - m['mean']) < 1e-12
        assert int(m.positive) == 20
        per_seed[budget] = vals.set_index('seed').difference
        printed[str(budget)] = dict(mean=float(m['mean']),
                                    ci_low=float(m.ci_low),
                                    ci_high=float(m.ci_high),
                                    positive=int(m.positive), n=int(m.n))
    # the paired design, drawn: one hairline per seed across the two windows
    seeds = sorted(set(per_seed[4096].index) & set(per_seed[16384].index))
    assert len(seeds) == 20
    fan = np.linspace(-0.09, 0.09, 20)
    order = {s_: k for k, s_ in enumerate(sorted(per_seed[4096].index))}
    for s_ in seeds:
        k = order[s_]
        ax.plot([0 + fan[k], 1 + fan[k]],
                [per_seed[4096][s_], per_seed[16384][s_]], color=color,
                lw=LW_HAIR, alpha=0.45, zorder=1.5)
    for i, budget in enumerate((4096, 16384)):
        v = per_seed[budget].sort_index()
        p = printed[str(budget)]
        seeds_and_mean(ax, i, v.to_numpy(), p['mean'], p['ci_low'],
                       p['ci_high'], color)
    ax.set_xlim(-.5, 1.5)
    ax.set_ylim(*UNIT_YLIM)
    ax.set_yticks([0, .5, 1], ['0', '0.5', '1'])
    ax.set_xticks([0, 1], ['4,096', '16,384'])
    reference_line(ax, 0.0, label=None)
    ax.annotate('no interaction', xy=(1.5, 0.0), xytext=(0.0, -1.4),
                textcoords='offset points', fontsize=PT_BASE, color=MUTE,
                ha='right', va='top', zorder=5)
    ax.set_xlabel('Window (updates)')
    ax.set_ylabel('(Broadcast − gate) NMSE:\nopposed − aligned')
    style_panel(ax)
    holm = float(t['audit']['primary_tests'][1]['holm_p'])
    assert abs(holm - 3.814697265625e-06) < 1e-15
    assert t['audit']['primary_tests'][1]['task'] == 'opposed_minus_aligned'
    # QA 2026-09-10 (visual review): the four-line block is deleted.  The
    # seed count and the Holm P value are the caption's own words ('n = 20
    # paired seeds ... prespecified sign-flip P = 3.8e-6 (Holm)') and the body
    # text's ('positive in all twenty seeds'), and 'opposed - aligned' now
    # names the plotted quantity where it belongs, on the y axis: the label
    # used to give the INNER difference only, so stripped of the in-plot line
    # the axis read as broadcast-minus-gate NMSE, which is 0.487 on opposed
    # targets alone and coincides with the plotted double difference only by
    # accident.  The head of the shared unit ladder drops to 1.15 with it.
    printed['annotation_lines'] = []
    printed['holm_p'] = holm
    printed['n_seeds'] = 20
    return printed


# ── F: gate shape versus gate placement ───────────────────────────────────
F_ORDER = ('exact', 'hard_distal_unit_proximal',
           'swapped_distal_unit_proximal', 'hard_distal_and_proximal')
F_LONG = ('Exact\npath', 'Distal\ngate', 'Swapped\ngate', 'Gate also\nproximal')
F_SHORT = ('Exact\npath', 'Distal\ngate', 'Swapped\ngate', 'Also\nproximal')
# QA 2026-09-10 (visual review).  The two gate SHAPES are dodged inside the
# distal-gate tick and the secondary-rate circles now hang off the TICK, one
# pair per category, instead of off each mark: dodged off both shapes they
# landed at -0.18 and +0.18, inside the other shape's cloud, and the open
# continuous diamond at +0.16 with a circle beyond it read as a fifth,
# unlabelled x position.  The continuous shape's own two rate means stay in
# the printed record and in Supplementary Fig. S21.
F_DODGE = 0.15          # the two gate shapes, either side of their own tick
F_RATE_DX = 0.40        # the secondary-rate circles, from the tick itself
F_FAN = 0.09            # per-seed cloud half-width
F_XLIM = (-0.55, 3.55)  # 0.15 wider than the outermost circle, which used to
                        # sit 1.7 pt inside the y spine and overlap it


def f_labels(ax):
    pitch = axes_w_pt(ax) / (ax.get_xlim()[1] - ax.get_xlim()[0])
    fits = all(_text_w_pt(ax, line, PT_BASE) <= pitch - 2.0
               for line in F_LONG[3].split('\n'))
    return F_LONG if fits else F_SHORT


def f_seeds(t, rule):
    ep = t['endpoints']
    return ep[(ep.task == 'opposed_strong') & (ep.rate == PRIMARY['rate'])
              & (ep.budget == PRIMARY['budget'])
              & (ep.rule == rule)].sort_values('seed')


def f_offset(rule):
    return {'hard_distal_unit_proximal': -F_DODGE,
            'shunt_proportional_unit_proximal': F_DODGE}.get(rule, 0.0)


def planned_marks(t):
    """Every mark F will draw, as (category index, x, value)."""
    marks = []
    for i, rule in enumerate(F_ORDER):
        offset = f_offset(rule)
        sel = f_seeds(t, rule)
        fan = np.linspace(-F_FAN, F_FAN, len(sel))
        marks += [(i, i + offset + dx, v) for dx, v in zip(fan, sel.test_nmse)]
        marks.append((i, i + offset, float(cond(t, 'opposed_strong', rule)['mean'])))
        for rate in (0.01, 0.10):
            marks.append((i, i + (-F_RATE_DX if rate == 0.01 else F_RATE_DX),
                          float(cond(t, 'opposed_strong', rule, rate=rate)['mean'])))
    cont = 'shunt_proportional_unit_proximal'
    sel = f_seeds(t, cont)
    fan = np.linspace(-F_FAN, F_FAN, len(sel))
    marks += [(1, 1 + F_DODGE + dx, v) for dx, v in zip(fan, sel.test_nmse)]
    marks.append((1, 1 + F_DODGE, float(cond(t, 'opposed_strong', cont)['mean'])))
    return marks


def placement(ax, t):
    printed = {}
    seeds = {}
    # DECISIONS (Fig 5) rules the rate marks as a build-time branch, not a
    # question: keep the three Adam rates everywhere unless adjacent
    # categories' marks come within 1.5 pt, and in that case keep them on the
    # exact-path and distal-gate categories only.
    ax.set_xlim(*F_XLIM)
    separation = cluster_separation(ax, planned_marks(t))
    rate_categories = (0, 1, 2, 3) if separation >= 1.5 else (0, 1)
    for i, rule in enumerate(F_ORDER):
        sel = f_seeds(t, rule)
        m = cond(t, 'opposed_strong', rule)
        offset = f_offset(rule)
        seeds_and_mean(ax, i + offset, sel.test_nmse, m['mean'], m.ci_low,
                       m.ci_high, rc(rule), fan=F_FAN)
        seeds[rule] = sel.test_nmse.to_numpy()
        printed[rule] = dict(mean=float(m['mean']), ci_low=float(m.ci_low),
                             ci_high=float(m.ci_high), n=int(m.n),
                             best_step_zero=int((sel.best_step == 0).sum()),
                             max_best_step=int(sel.best_step.max()),
                             both_gains_frozen=int(((~sel.g_i0_changed)
                                                    & (~sel.g_i1_changed)).sum()),
                             min_changed_parameters=int(sel.n_changed_parameters.min()),
                             mean_fixed_endpoint=float(m.mean_fixed_endpoint))
        # the two secondary rates, mean only
        for rate in (0.01, 0.10):
            mm = cond(t, 'opposed_strong', rule, rate=rate)
            if i in rate_categories:
                ax.plot([i + (-F_RATE_DX if rate == 0.01 else F_RATE_DX)],
                        [mm['mean']], marker='o', ms=3.0, mfc='white',
                        mec=rc(rule), mew=LW_EDGE, ls='none', zorder=3.5)
            printed[rule][f'rate_{rate}'] = float(mm['mean'])
    # the continuous SHAPE of the same rule, paired inside the Distal gate
    # tick.  QA 2026-09-10 (visual review): its twenty seeds are drawn.  The
    # table holds them and the panel used to plot the mean alone, so one of
    # the two shapes the panel equates showed a cloud and the other did not.
    cont_sel = f_seeds(t, 'shunt_proportional_unit_proximal')
    cont = cond(t, 'opposed_strong', 'shunt_proportional_unit_proximal')
    seeds_and_mean(ax, 1 + F_DODGE, cont_sel.test_nmse, cont['mean'],
                   cont.ci_low, cont.ci_high, COLORS['shunting'], fan=F_FAN,
                   mfc='white', mec=COLORS['shunting'], mew=LW_ERR)
    printed['shunt_proportional_unit_proximal'] = {
        'mean': float(cont['mean']), 'ci_low': float(cont.ci_low),
        'ci_high': float(cont.ci_high), 'n': int(cont.n),
        'rate_0.01': float(cond(t, 'opposed_strong',
                                'shunt_proportional_unit_proximal',
                                rate=0.01)['mean']),
        'rate_0.1': float(cond(t, 'opposed_strong',
                               'shunt_proportional_unit_proximal',
                               rate=0.10)['mean'])}
    # the assertions the plan names
    assert printed['swapped_distal_unit_proximal']['best_step_zero'] == 4
    assert printed['hard_distal_and_proximal']['both_gains_frozen'] == 20
    assert printed['hard_distal_and_proximal']['max_best_step'] == 256
    for rule in ('exact', 'hard_distal_unit_proximal'):
        assert printed[rule]['min_changed_parameters'] == 24
    broadcast = cond(t, 'opposed_strong', 'unit_broadcast')['mean']
    assert abs(broadcast - 0.48740) < 5e-5
    ax.set_xlim(*F_XLIM)
    ax.set_yscale('log')
    ax.set_ylim(*LOG_YLIM)
    ax.set_xticks(range(4), f_labels(ax))
    ax.set_ylabel('Opposed NMSE')
    style_panel(ax)
    plain_log_ticks(ax)          # after style_panel: it resets the tick pad
    ax.tick_params(axis='x', labelsize=PT_BASE, pad=2.0)
    reference_line(ax, broadcast, label=None)
    # under its own rule: set above it the 7-pt label reads at the height of
    # the swapped-gate mean, which it does not name
    ax.annotate(f'unit broadcast {broadcast:.2f}', xy=(F_XLIM[0], broadcast),
                xytext=(1.0, -3.8), textcoords='offset points',
                fontsize=PT_BASE, color=MUTE, ha='left', va='top', zorder=5)
    # QA 2026-09-10 (visual review): the three key lines are deleted.  CF-5
    # sanctions exactly ONE in-axes key in the nine-figure set (C's four-entry
    # rule key), these were a second, and they held three decades of empty
    # head over the data.  The filled/open shape pair is named in the caption
    # and the pair itself carries the panel's own 'hard = continuous' label.
    # The two column qualifications stay, each in a band no mark enters.
    # QA 2026-09-10 (visual review): the swapped mean is printed with the
    # qualification.  It sits 0.29 decade over the unit-broadcast rule -- four
    # points at this scale, less than the diamond's own half-height -- so a
    # near-twofold difference in failure reads off the panel as coincidence.
    swapped = printed['swapped_distal_unit_proximal']
    stack(ax, 0.99, 0.44,
          [f"{swapped['mean']:.2f}; {swapped['best_step_zero']}/20 unchanged",
           'from initialization'], ha='right', lead_pt=8.6)
    tie_leader(ax, 2.0, 0.44, seeds['swapped_distal_unit_proximal'].min())
    also = printed['hard_distal_and_proximal']
    # two right-aligned lines over the column they name, in the band the
    # failure cluster leaves under the panel title
    frozen = [['g', ('sub', 'I'), f" frozen {also['both_gains_frozen']}/20"],
              f"best step ≤ {also['max_best_step']}, "
              f"endpoint {also['mean_fixed_endpoint']:.2f}"]
    _, below = stack(ax, 0.99, 0.955, frozen, ha='right', lead_pt=8.6)
    # QA 2026-09-11 (regression check): both column tags are right-edge
    # blocks now, and only the swapped one kept a leader when the frozen
    # block moved up from 0.300 (its old upward tie at x = 3.0 went with the
    # move), so its attribution rested on also-proximal being the rightmost
    # category.  The tie is back, running DOWN from the block's bottom line
    # to 2.2 pt over the highest mark in the column it names.
    also_sel = f_seeds(t, 'hard_distal_and_proximal')
    also_m = cond(t, 'opposed_strong', 'hard_distal_and_proximal')
    tie_leader(ax, 3.0, below + 8.6 / axes_h_pt(ax),
               max(float(also_sel.test_nmse.max()), float(also_m.ci_high)),
               above=True)
    # PLAN section 2 (F, 'Printed on panel'): the equality the panel title
    # asserts is said in words, not left to the two coincident diamonds.  The
    # between-cluster band is spent on the swapped-gate tie, so the line takes
    # the free band directly under the Distal gate pair (lowest mark there is
    # 4.8e-6, y frac 0.176; this line is centred at 0.085).
    assert abs(printed['hard_distal_unit_proximal']['mean']
               - cont['mean']) / cont['mean'] < 0.02
    stack(ax, x_frac(ax, 1.0), 0.075, ['hard = continuous'], ha='center',
          color=COLORS['shunting'])
    printed['unit_broadcast_reference'] = float(broadcast)
    printed['_min_mark_separation_pt'] = round(separation, 2)
    printed['_rate_categories'] = [F_ORDER[i] for i in rate_categories]
    return printed


def tie_leader(ax, x, y_edge_frac, datum, *, gap_pt=2.2, above=False):
    """Hairline from just outside a tied annotation to just short of its cluster.

    The plan's rule is ``y_text < y_lead < lowest``: the leader starts at the
    text box, not inside it, and stops short of the lowest datum of the
    column it names.  ``above=True`` is the mirror case (QA 2026-09-11): the
    tag sits over its column, ``y_edge_frac`` is its BOTTOM line and
    ``datum`` the highest mark, and the leader runs down to it.
    """
    h = axes_h_pt(ax)
    if above:
        y0 = y_edge_frac - (0.5 * PT_BASE + gap_pt) / h
        y1 = y_frac(float(datum)) + gap_pt / h
        y0, y1 = y1, y0
    else:
        y0 = y_edge_frac + (0.5 * PT_BASE + gap_pt) / h
        y1 = y_frac(float(datum)) - gap_pt / h
    if y1 - y0 < 1.5 / h:
        return None
    line, = ax.plot([x, x], [y_data(y0), y_data(y1)], color=MUTE,
                    lw=LW_HAIR, zorder=2)
    return line


def mark_points(ax, marks):
    """(category, x, value) marks as (category, x_pt, y_pt) on this axes."""
    w, h = axes_w_pt(ax), axes_h_pt(ax)
    x0, x1 = ax.get_xlim()
    lo, hi = (math.log10(v) for v in LOG_YLIM)
    return [(cat, (x - x0) / (x1 - x0) * w,
             (math.log10(v) - lo) / (hi - lo) * h) for cat, x, v in marks]


def cluster_separation(ax, marks):
    """Closest pair of marks belonging to two DIFFERENT categories, in points.

    This is the quantity the plan's F fallback is written against ('if
    min_separation_pt between adjacent category clusters falls below 1.5 pt,
    drop the two secondary-rate circles ...'): the categories are separated
    along x, so what can collide is a mark of one category with a mark of its
    neighbour, not the value RANGES, which overlap by construction wherever
    two rules succeed equally.
    """
    pts = mark_points(ax, marks)
    worst = float('inf')
    for i, (ca, xa, ya) in enumerate(pts):
        for cb, xb, yb in pts[i + 1:]:
            if abs(ca - cb) != 1:
                continue
            worst = min(worst, math.hypot(xa - xb, ya - yb))
    return float(worst)


# ── G: context-gradient cancellation (earlier cohort) ─────────────────────
def cancellation(ax, t):
    h = t['historical']
    assert len(h) == 80 and set(h.historical_seed) == set(range(2101, 2121))
    rng = np.random.default_rng(HIST_SEED)
    printed = {}
    fan = np.linspace(-.055, .055, 20)
    for rule, offset, marker, ckey, mfc in (
            ('exact', -.14, 'o', 'bp', None),
            ('calibrated_broadcast', .14, 's', 'scalar', 'white')):
        color = COLORS[ckey]
        paired = {}
        for i, state in enumerate(('initial', 'extended_best')):
            part = h[(h.state == state) & (h.evaluated_rule == rule)
                     & (h.source_rule == 'calibrated_broadcast')
                     ].sort_values('historical_seed')
            assert len(part) == 20
            vals = part.context_cancellation_ratio.to_numpy()
            lo, hi = boot(vals, rng)
            seeds_and_mean(ax, i + offset, vals, vals.mean(), lo, hi, color,
                           marker=marker, fan=.055,
                           mfc='white' if mfc else color,
                           mec=color if mfc else 'white',
                           mew=LW_ERR if mfc else LW_HAIR)
            paired[state] = vals
            printed[f'{rule}_{state}'] = dict(mean=float(vals.mean()),
                                              ci_low=float(lo),
                                              ci_high=float(hi), n=len(vals))
        # QA 2026-09-10 (visual review): the states are paired within a seed,
        # so they are joined seed by seed as in E.  The mean-to-mean rule this
        # replaces ran flat for exact credit (0.6364 to 0.6365) and read as
        # 'nothing moved', while five of the twenty seeds fall below 0.17 at
        # the trained state -- the split the hairlines now show.
        for k in range(20):
            ax.plot([offset + fan[k], 1 + offset + fan[k]],
                    [paired['initial'][k], paired['extended_best'][k]],
                    color=color, lw=LW_HAIR, alpha=0.32, zorder=1.5)
    assert abs(printed['exact_initial']['mean'] - 0.636) < 2e-3
    assert abs(printed['exact_extended_best']['mean'] - 0.637) < 2e-3
    assert abs(printed['calibrated_broadcast_initial']['mean'] - 0.330) < 2e-3
    assert abs(printed['calibrated_broadcast_extended_best']['mean'] - 0.172) < 2e-3
    up = t['upstream']
    sel = up[(up.task == 'opposed_strong')
             & (up.parameter_scope == 'distal_parameters')
             & (up.source_rule == 'calibrated_broadcast')
             & (up.state.isin(['initial', 'extended_best']))
             & (up.evaluated_rule.isin(['exact', 'calibrated_broadcast']))]
    assert len(sel) == 80
    positive = int((sel.min_example_gradient_inner_product > 0).sum())
    assert positive == 80
    printed['min_example_inner_product'] = float(
        sel.min_example_gradient_inner_product.min())
    ax.set_xlim(-.5, 1.5)
    ax.set_ylim(*UNIT_YLIM)
    ax.set_yticks([0, .5, 1], ['0', '0.5', '1'])
    ax.set_xticks([0, 1], ['Initial', 'Trained'])
    ax.tick_params(axis='x', labelsize=PT_BASE, pad=2.0)
    # QA 2026-09-10 (visual review): the rule's own label is set under its
    # LEFT end, the only place in this panel no seed and no hairline reaches,
    # which frees the band over the trained column for the exact-credit label.
    reference_line(ax, 1.0, label=None)
    ax.annotate('no cancellation', xy=(-0.5, 1.0), xytext=(1.0, -1.4),
                textcoords='offset points', fontsize=PT_BASE, color=MUTE,
                ha='left', va='top', zorder=5)
    ax.set_ylabel('Distal gradient retained')
    style_panel(ax)
    # direct labels in the corridor the two seed columns leave open
    # QA 2026-09-11 (regression check): 'exact credit' used to sit ABOVE the
    # rule at (1.5, 1.07), flush with the right spine (0.1 pt) and reading as
    # a retained-fraction claim for a series whose trained mean is 0.63.  It
    # cannot go under the rule over the trained column either: five trained
    # seeds lie at 0.92-0.98 and the amber seed at 0.81 leaves no 7-pt line
    # to their right.  So it is set like the amber label -- two lines under
    # its own initial cloud (lowest seed 0.494, top edge here 0.428), left of
    # the amber initial seeds (x >= 0.071) by 4 pt.
    lo_y, hi_y = UNIT_YLIM
    stack(ax, (-0.19 + 0.5) / 2.0, (0.39 - lo_y) / (hi_y - lo_y),
          ['exact', 'credit'], ha='center', color=COLORS['bp'], lead_pt=8.2)
    # QA 2026-09-09 (2): set through stack() at the figure's 8.6 pt leading
    # (the hand-placed data-unit pair was 6.0 pt and the boxes overlapped)
    stack(ax, (0.44 + 0.5) / 2.0, (-0.025 - lo_y) / (hi_y - lo_y),
          ['calibrated', 'broadcast'], ha='center', color=AMBER_TEXT,
          lead_pt=8.2)
    # QA 2026-09-10 (visual review): the four-line tag is deleted.  'earlier
    # cohort, n = 20 (seeds 2101-2120)' is the caption's own words and the
    # nonnegative per-example alignment is the body text's ('a nonnegative
    # per-example inner product with the exact gradient in every seed'); the
    # band it occupied above 1.0 was half this panel's empty height.
    printed['n_seeds'] = 20
    return printed


# ── assembly ──────────────────────────────────────────────────────────────
def build(cfg, tables, tuning):
    canvas = NativeCanvas(HEIGHT_PT / 72, 3, row_weights=ROWS_PT,
                          hgutter_pt=HGUTTER_PT, vgutter_pt=VGUTTER_PT,
                          margins=Margins(**MARGINS))
    # the letter column moves out to 26 pt so the y-label stacks of C and E can
    # sit INSIDE their slots, right of the letters, instead of hanging into the
    # left margin (audit_letter_alignment's second check)
    canvas.letter_dx = LETTER_DX_PT
    a = canvas.panel('A', 0, 0, 5, schematic=True, lock=False,
                     title='Context shunts one branch')
    b = canvas.panel('B', 0, 5, 7, schematic=True, lock=False,
                     title='Four deliveries of the somatic error')
    c = canvas.panel('C', 1, 0, 6, title='Aligned: every rule learns')
    d = canvas.panel('D', 1, 6, 6, title='Opposed: broadcast fails')
    e = canvas.panel('E', 2, 0, 4, title='Task-specific gate benefit')
    f_ = canvas.panel('F', 2, 4, 4, title='Placement, not gate shape')
    g = canvas.panel('G', 2, 8, 4, title='Context gradients cancel')
    data_panels = ('C', 'D', 'E', 'F', 'G')
    for n in data_panels:
        canvas.declare_reserve(n, left=LEFT_RESERVE_PT, right=RIGHT_RESERVE_PT,
                               top=ROW2_TOP_PT if n in ('E', 'F', 'G') else 0.0,
                               bottom=0.0)
    canvas.lock_reserves()
    task = panel_task(a, tuning)
    panel_deliveries(b)
    curves(c, tables, 'aligned_strong', legend=True)
    curves(d, tables, 'opposed_strong')
    printed = dict(A=dict(perturbation_line=task['perturbation']),
                   C=curve_annotations(c, tables, 'aligned_strong'),
                   D=curve_annotations(d, tables, 'opposed_strong'),
                   E=interaction(e, tables),
                   F=placement(f_, tables),
                   G=cancellation(g, tables))
    axis_break(c, 64.0)
    axis_break(d, 64.0)
    # the oracle badge, pinned in points to C's axes corner after its entry
    canvas.fig.canvas.draw()
    r = canvas.fig.canvas.get_renderer()
    box = c._oracle_entry.get_window_extent(r)
    corner = c.transAxes.transform((0.0, 0.0))
    k = 72.0 / canvas.fig.dpi
    badge_at(c, (0.0, 0.0), 'oracle', xycoords='axes fraction',
             offset_pt=((box.x1 - corner[0]) * k + 3.0,
                        ((box.y0 + box.y1) / 2 - corner[1]) * k),
             ha='left', va='center')
    # one axes width per span family: declare the widest left / right need of
    # any data panel for all of them, so C = D and E = F = G exactly.
    # the y-label stack has to sit inside the slot, right of the letter
    # column: verified, not assumed (audit_letter_alignment's second check)
    canvas.lock_reserves()
    canvas.fig.canvas.draw()
    renderer = canvas.fig.canvas.get_renderer()
    scale = 72.0 / canvas.fig.dpi
    overhang = 0.0
    for n in data_panels:
        ax = canvas.axes[n]
        bb = ax.yaxis.get_tightbbox(renderer)
        if bb is None or bb.width <= 0:
            continue
        overhang = max(overhang, ax.get_position().x0 * canvas.width_pt
                       - bb.x0 * scale)
    column_end = (canvas.letter_x_pt(0) + LETTER_CAP_FRAC * 9.0
                  + LETTER_GAP_PT)
    need = column_end + 1.2 + overhang - canvas.margins.left
    assert need <= LEFT_RESERVE_PT + 1e-6, (
        f'left reserve {LEFT_RESERVE_PT} pt is {need - LEFT_RESERVE_PT:.1f} pt '
        f'short of the letter column')
    inset_frame = [task['inset'].patch] + list(task['inset'].get_yticklabels())
    gap = min_separation_pt(canvas.fig, task['gate_tag'], inset_frame)
    assert gap >= 3.0, f'A: closed-gate tag clears the inset by {gap:.1f} pt'
    printed['A']['gate_tag_to_inset_pt'] = round(gap, 2)
    printed['_geometry'] = dict(
        height_pt=HEIGHT_PT, rows_pt=list(ROWS_PT),
        schematic_fraction_b12=round(SCHEMATIC_FRACTION, 4),
        g4_waiver=G4_WAIVER, in_axes_key_exception=KEY_EXCEPTION)
    findings = list(canvas.save(PDF, name='local_gate_primary', dpi=180))
    audit = [str(v) for v in audit_native_pdf(PDF, strict=True)]
    return printed, findings, audit


# ── provenance ────────────────────────────────────────────────────────────
PANEL_SOURCES = {
    'main_5A': ['scripts/conductance_local_gate/model.py',
                'source_data/conductance_local_gate/METHODS.md',
                'source_data/conductance_local_gate/figures/teacher_tuning_source.csv'],
    'main_5B': ['scripts/conductance_local_gate/model.py',
                'source_data/conductance_local_gate/METHODS.md'],
    'main_5C': ['source_data/conductance_local_gate/figures/curve_band_source.csv',
                'source_data/conductance_local_gate/summaries/all_curves.csv'],
    'main_5D': ['source_data/conductance_local_gate/figures/curve_band_source.csv',
                'source_data/conductance_local_gate/summaries/all_curves.csv',
                'source_data/conductance_local_gate/summaries/condition_means.csv'],
    'main_5E': ['source_data/conductance_local_gate/summaries/paired_contrasts.csv',
                'source_data/conductance_local_gate/summaries/paired_seed_contrasts.csv',
                'source_data/conductance_local_gate/summaries/completeness_audit.json'],
    'main_5F': ['source_data/conductance_local_gate/summaries/all_endpoints.csv',
                'source_data/conductance_local_gate/summaries/condition_means.csv'],
    'main_5G': ['source_data/conductance_local_gate/figures/historical_cancellation_source.csv',
                'source_data/conductance_credit_demand/opponent/summaries/context_gradient_summary.csv'],
}
PANEL_SCOPE = {
    'main_5A': 'Seven-compartment circuit, E/I contacts, the context gate and the local distal gate’s addressed subtree; inset: nominal unperturbed teacher terminal voltage against the latent feature. Schematic, no data.',
    'main_5B': 'The four deliveries of the somatic error defined by model.delivered (local distal gate, exact path, unit broadcast, two-profile oracle). The oracle has two fixed nonuniform distal profiles p1/p2 with exact-field amplitudes c1/c2, and unit proximal/somatic multipliers. Its equal terminal dots identify support sites, not weight magnitude. Schematic, no data.',
    'main_5C': 'Aligned targets, Adam 0.03, four prespecified rules, 20 paired simulation seeds; means with 95 % pointwise whole-seed bootstrap bands at 12 fixed checkpoints.',
    'main_5D': 'Opposed targets, same cohort and readout as C; bound-contact mark from all_curves.first_bound_step; validation-selected broadcast mean from condition_means.',
    'main_5E': 'Opposed-minus-aligned difference of broadcast-minus-gate NMSE at both windows, validation-selected states, 20 paired seeds joined across windows; prespecified sign-flip test, Holm-adjusted.',
    'main_5F': 'Opposed NMSE at validation-selected states within the 4,096-update window: exact path, the local distal gate in its hard and continuous shapes, the swapped gate and the gate-also-proximal control, at all three Adam rates.',
    'main_5G': 'Earlier cohort seeds 2101–2120; fraction of the distal-parameter gradient retained after context averaging at matched initial and broadcast-trained weight states.',
}


def display_rows(tables, printed):
    rows = []
    tuning = pd.read_csv(FIG / 'teacher_tuning_source.csv',
                         float_precision='round_trip')
    for _, r in tuning.iterrows():
        rows.append(dict(panel='A', record='nominal teacher',
                         latent_feature=r.z, increasing=r.v_increasing,
                         decreasing=r.v_decreasing))
    band = tables['band']
    for panel, task in (('C', 'aligned_strong'), ('D', 'opposed_strong')):
        sel = band[(band.task == task) & (band.rate == PRIMARY['rate'])
                   & (band.rule.isin(CURVE_RULES))].sort_values(['rule', 'step'])
        for _, r in sel.iterrows():
            rows.append(dict(panel=panel, record='curve band', task=r.task,
                             rule=r.rule, rate=r.rate, step=r.step,
                             mean=r['mean'], ci_low=r.ci_low,
                             ci_high=r.ci_high))
    s = tables['seed_contrasts']
    for budget in (4096, 16384):
        sel = s[(s.task == 'opposed_minus_aligned') & (s.rate == PRIMARY['rate'])
                & (s.budget == budget) & (s.left == 'unit_broadcast')
                & (s.right == 'hard_distal_unit_proximal')].sort_values('seed')
        for _, r in sel.iterrows():
            rows.append(dict(panel='E', record='paired seed difference',
                             task=r.task, budget=r.budget, rate=r.rate,
                             left=r.left, right=r.right, seed=r.seed,
                             difference=r.difference))
        p = printed['E'][str(budget)]
        rows.append(dict(panel='E', record='paired contrast',
                         task='opposed_minus_aligned', budget=budget,
                         rate=PRIMARY['rate'], left='unit_broadcast',
                         right='hard_distal_unit_proximal', n=p['n'],
                         mean=p['mean'], ci_low=p['ci_low'],
                         ci_high=p['ci_high'], positive=p['positive']))
    ep = tables['endpoints']
    f_rules = list(F_ORDER) + ['shunt_proportional_unit_proximal',
                               'unit_broadcast']
    for rate in RATES:
        sel = ep[(ep.task == 'opposed_strong') & (ep.budget == PRIMARY['budget'])
                 & (ep.rate == rate) & (ep.rule.isin(f_rules))
                 ].sort_values(['rule', 'seed'])
        for _, r in sel.iterrows():
            rows.append(dict(panel='F', record='endpoint', task=r.task,
                             budget=r.budget, rate=r.rate, rule=r.rule,
                             seed=r.seed, best_step=r.best_step,
                             test_nmse=r.test_nmse,
                             fixed_endpoint_test_nmse=r.fixed_endpoint_test_nmse,
                             n_changed_parameters=r.n_changed_parameters,
                             g_i0_changed=r.g_i0_changed,
                             g_i1_changed=r.g_i1_changed))
        for rule in f_rules:
            m = cond(tables, 'opposed_strong', rule, rate=rate)
            rows.append(dict(panel='F', record='condition mean',
                             task='opposed_strong', budget=PRIMARY['budget'],
                             rate=rate, rule=rule, n=int(m.n), mean=m['mean'],
                             ci_low=m.ci_low, ci_high=m.ci_high,
                             mean_fixed_endpoint=m.mean_fixed_endpoint))
    h = tables['historical'].sort_values(['evaluated_rule', 'state',
                                          'historical_seed'])
    for _, r in h.iterrows():
        rows.append(dict(panel='G', record='context cancellation',
                         seed=r.historical_seed, state=r.state,
                         rule=r.evaluated_rule,
                         value=r.context_cancellation_ratio))
    return rows


def figure_provenance(cfg, printed, problems, audit):
    files = [FIG / name for name in
             ['local_gate_primary.pdf', 'local_gate_primary.png',
              'local_gate_all_rates.pdf', 'local_gate_all_rates.png',
              'curve_band_source.csv', 'historical_cancellation_source.csv',
              'teacher_tuning_source.csv']]
    inputs = list(sorted((OUT / 'summaries').glob('*.csv'))) + [
        OUT / 'protocol.json', OUT / 'protocol_freeze.json',
        J / 'source_data/conductance_credit_demand/opponent/summaries/context_gradient_summary.csv']
    code = [Path(__file__), Path(__file__).with_name('report.py'),
            Path(__file__).with_name('portable_contract.py'),
            Path(__file__).with_name('model.py'),
            J / 'scripts/journal_style.py', J / 'scripts/figure_canvas.py',
            J / 'scripts/native_schematics.py',
            J / 'scripts/credit_tree_schematics.py']

    def hashes(paths):
        return {str(p.relative_to(J)): digest(p) for p in paths}
    record = dict(
        status='PASS',
        scope='Current figure-only rendering; frozen protocol and numerical '
              'summary bytes unchanged. Initial numerical audit retains its '
              'historical render hashes.',
        protocol_sha256=digest(OUT / 'protocol.json'),
        fresh_seeds=cfg['fresh_seeds'],
        historical_seeds=list(range(2101, 2121)),
        figure_sha256=hashes(files), input_sha256=hashes(inputs),
        code_sha256=hashes(code),
        panel_sources={key: {'type': 'schematic' if key in ('main_5A', 'main_5B')
                             else ('historical cohort' if key == 'main_5G'
                                   else 'fresh cohort'),
                             'sources': PANEL_SOURCES[key],
                             'scope': PANEL_SCOPE[key]}
                       for key in PANEL_SOURCES},
        printed_numbers=printed,
        native_canvas=dict(height_pt=HEIGHT_PT, rows_pt=list(ROWS_PT),
                           schematic_fraction_b12=round(SCHEMATIC_FRACTION, 4),
                           g4_waiver=G4_WAIVER,
                           in_axes_key_exception=KEY_EXCEPTION,
                           layout_findings=problems,
                           strict_audit_violations=audit),
    )
    record['source_sha256'] = {**record['input_sha256'], **record['code_sha256']}
    (OUT / 'figure_provenance.json').write_text(
        json.dumps(record, indent=2, sort_keys=True) + '\n')
    return record


def main():
    cfg, freeze, _ = load_protocol()
    audit = json.loads((OUT / 'summaries/completeness_audit.json').read_text())
    assert audit['status'] == 'PASS'
    folder = OUT / 'summaries'
    for relative, original in audit['summary_sha256'].items():
        verify(OUT / relative, original)
    frames = {k: pd.read_csv(folder / f'all_{k}.csv', float_precision='round_trip')
              for k in ['endpoints', 'curves', 'diagnostics']}
    means = pd.read_csv(folder / 'condition_means.csv',
                        float_precision='round_trip')
    contrasts = pd.read_csv(folder / 'paired_contrasts.csv',
                            float_precision='round_trip')
    import report
    _save = report.save

    def save_all_rates_only(fig, name):
        if name == 'local_gate_primary':
            matplotlib.pyplot.close(fig)
            return
        _save(fig, name)
    with mock.patch.object(report, 'save', save_all_rates_only):
        figures(cfg, frames, means, contrasts)
    tuning = teacher_tuning()
    tables = load_tables()
    printed, problems, strict = build(cfg, tables, tuning)
    figure_provenance(cfg, printed, problems, strict)
    focused_provenance.publish(
        5, PDF, display_rows(tables, printed),
        sources=[J / p for p in sorted({p for v in PANEL_SOURCES.values()
                                        for p in v})],
        builders=[Path(__file__), Path(__file__).with_name('report.py'),
                  Path(__file__).with_name('model.py'),
                  J / 'scripts/figure_canvas.py',
                  J / 'scripts/native_schematics.py',
                  J / 'scripts/journal_style.py'],
        panels={key: {'sources': PANEL_SOURCES[key], 'scope': PANEL_SCOPE[key]}
                for key in PANEL_SOURCES},
        emit_main=True, layout_findings=problems,
        notes=('Main Figure 5 (fig:conductancecredit), overhaul v2. '
               + G4_WAIVER + ' ' + KEY_EXCEPTION))
    for line in problems:
        print('layout:', line)
    for line in strict:
        print('strict audit:', line)
    print('Native figures redrawn; experiment protocol and numerical summary '
          'files unchanged.')


if __name__ == '__main__':
    main()
