"""Loss functions for dendritic modeling."""

from .bio_losses import (
    compute_bio_losses,
    loss_dog,
    loss_dsi,
    loss_endstop,
    loss_osi,
    loss_phase_invariance,
    loss_sparsity,
)
from .functions import (
    BCELoss,
    CategoricalNLLLoss,
    CrossEntropyLoss,
    LogAdjustedNegativeCosineSimilarityLoss,
    LogMSELoss,
    LossFunction,
    MaskedDualTaskTemporalLoss,
    MSELoss,
    NegativeCosineSimilarityLoss,
    TemporalEventCrossEntropyLoss,
    VaeElboLoss,
    VoltageStabilizationLoss,
    get_available_loss_functions,
    get_loss_function,
    register_loss_function,
    unregister_loss_function,
)

__all__ = [
    "BCELoss",
    "CategoricalNLLLoss",
    "CrossEntropyLoss",
    "LogAdjustedNegativeCosineSimilarityLoss",
    "LogMSELoss",
    "LossFunction",
    "MSELoss",
    "MaskedDualTaskTemporalLoss",
    "NegativeCosineSimilarityLoss",
    "TemporalEventCrossEntropyLoss",
    "VaeElboLoss",
    "VoltageStabilizationLoss",
    "compute_bio_losses",
    "get_available_loss_functions",
    "get_loss_function",
    "loss_dog",
    "loss_dsi",
    "loss_endstop",
    "loss_osi",
    "loss_phase_invariance",
    "loss_sparsity",
    "register_loss_function",
    "unregister_loss_function",
]
