#!/usr/bin/env python3
"""Supplementary Fig. S1 -- the regular-tree mechanistic chain -- rebuilt as
ONE native full-width canvas in the journal style.

The inherited sheet (preserved byte for byte at
``figures/supplementary/inherited/figure_S01_panels_A-E.pdf``) was a five-
across NeurIPS strip generated by
``scripts/inherited_neurips/generate_theory_diagnostics_figures.py``.  This
builder re-lays the SAME five panels (same letters, same content, same frozen
numbers) onto a two-row 12-module :class:`figure_canvas.NativeCanvas`:

* row 0 -- A the conductance-stage path-gain field with the paired-seed CV
  inset; B the stage-resolved submitted-field cosine on distal/proximal
  compartments; C the post-training inhibition interventions;
* row 1 -- D feedback fidelity and E learning on the noise-resilience task
  (solid = matched-width/scalar-fallback feedback, dashed = exact transported
  error; whiskers are +-1 s.d., exactly the statistic the archived generator
  shaded as a band).

Every plotted number is the archived one: the aggregations below are ported
verbatim from the frozen generator (same CSVs, same filters, same groupbys,
same ddof), and the build prints the endpoint values it draws so they can be
diffed against the frozen tables.  Only layout, palette mapping and label
wording are native:

* shunting keeps the house green circle and additive the house blue square in
  every panel; linestyle (solid/dashed) carries the feedback condition in
  D/E, exactly as the caption reads the figure;
* the panel-A path colormap is the house sequential ramp instead of viridis,
  over the identical data-derived normalisation;
* panel C drops its legend box for direct per-bar labels on the MNIST group
  (the Noise group repeats the same five interventions in the same order);
* no mathtext: subscripts are unicode so the strict type audit passes.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.colors as mcolors
import numpy as np
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from figure_canvas import (  # noqa: E402
    COLORS,
    ERR_CAPSIZE,
    LW_DATA,
    LW_EDGE,
    LW_ERR,
    LW_HAIR,
    MARKER_MS,
    PT_ANNOT,
    PT_LEGEND,
    PT_SMALL,
    PT_TICK,
    SEQ_CMAP,
    NativeCanvas,
    style_panel,
)

ROOT = SCRIPT_DIR.parent
SRC = ROOT / "source_data" / "inherited_neurips"
OUT = ROOT / "figures" / "supplementary" / "figure_S01_panels_A-E.pdf"

SUMMARY_CSV = SRC / "theory_diag_by_condition.csv"
PATH_GAIN_SEED_CSV = SRC / "path_gain_cv_mnist_ni5_seed.csv"
ORACLE_SUMMARY_CSV = SRC / "path_transport_upper_bound_summary.csv"
DECOMPOSITION_RUNS_CSV = SRC / "error_field_decomposition_runs.csv"
INHIBITION_CAUSALITY_CSV = SRC / "inhibition_causality_runs.csv"

SHUNT = COLORS["shunting"]
ADD = COLORS["additive"]
INK = COLORS["ink"]
MUTE = COLORS["mute"]

CORE_MARKER = {"dendritic_shunting": "o", "dendritic_additive": "s"}
CORE_COLOR = {"dendritic_shunting": SHUNT, "dendritic_additive": ADD}
CORE_WORD = {"dendritic_shunting": "shunting", "dendritic_additive": "additive"}

# Shared axes for the two noise-resilience sweeps (D, E): identical x
# geometry so the reader carries the N_I positions across the pair.
IE_TICKS = [0, 20, 40]
IE_XLIM = (-2.0, 56.0)
IE_XLABEL = "inhibitory synapses per branch"


def _csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(path)
    return pd.read_csv(path)


# ── panel A: conductance-stage path-gain field ───────────────────────────
def _path_cmap(t: float):
    """House sequential ramp, clipped away from its near-white foot so the
    lowest-gain path still prints as a visible stroke."""
    return SEQ_CMAP(0.30 + 0.68 * float(t))


def _draw_gain_tree(ax, *, x0, name, cv, gains, tone, norm, label_soma):
    """Compact three-path tree colored by log path gain (frozen geometry)."""
    soma = (x0 + 0.32, 0.52)
    branch_x = x0 + 0.15
    leaf_x = x0 + 0.02
    ys = [0.78, 0.52, 0.26]
    for idx, y in enumerate(ys):
        log_gain = np.log10(max(gains[idx], 1e-5))
        line_color = _path_cmap(norm(log_gain))
        ax.plot([leaf_x, branch_x, soma[0]], [y, y, soma[1]],
                color=line_color, linewidth=LW_DATA,
                solid_capstyle="round", zorder=2)
        ax.scatter([leaf_x], [y], s=16.0, facecolor=line_color,
                   edgecolor="white", linewidth=LW_HAIR, zorder=4)
        ax.text(leaf_x - 0.025, y, f"α{chr(0x2081 + idx)}", ha="right",
                va="center", fontsize=PT_TICK, color=INK, zorder=6,
                bbox={"facecolor": "white", "edgecolor": "none",
                      "pad": 0.6, "alpha": 0.88})
    ax.scatter([soma[0]], [soma[1]], s=52.0, facecolor=COLORS["soma"],
               edgecolor=COLORS["edge"], linewidth=LW_EDGE, zorder=5)
    if label_soma:
        ax.text(soma[0] + 0.015, soma[1] + 0.085, "δ₀", ha="left",
                va="bottom", fontsize=PT_TICK, color=INK, zorder=6)
    ax.text(x0 + 0.17, 0.905, f"{name}\n{cv:.2f}", ha="center", va="center",
            fontsize=PT_LEGEND, color=tone, linespacing=1.0)


def panel_path_gains(ax, summary, path_gain_seed):
    """A: path-gain field at N_I = 5 with the paired-seed CV inset.

    The two aggregate CVs and the deterministic gain spread they set, the
    seed-level pivot, the bar means and the ddof=1 s.d. are ported verbatim
    from ``_plot_path_gain_map`` in the frozen generator.
    """
    ax.set_xlim(0, 1.0)
    ax.set_ylim(0, 1.0)

    mnist = summary[summary["dataset"] == "mnist"].copy()
    add_cv = float(
        mnist[(mnist["network_type"] == "dendritic_additive")
              & (mnist["ie_value"] == 5)]["path_gain_cv_mean_mean"].iloc[0])
    shunt_cv = float(
        mnist[(mnist["network_type"] == "dendritic_shunting")
              & (mnist["ie_value"] == 5)]["path_gain_cv_mean_mean"].iloc[0])

    # Data-scaled representative path gains: larger CV, broader spread.
    add_gains = [1.0 - add_cv / 3.0, 1.0, 1.0 + add_cv]
    shunt_gains = [1.0 - shunt_cv / 3.0, 1.0, 1.0 + shunt_cv]
    all_logs = np.log10(np.clip(add_gains + shunt_gains, 1e-5, None))
    norm = mcolors.Normalize(vmin=float(all_logs.min()),
                             vmax=float(all_logs.max()))

    _draw_gain_tree(ax, x0=0.03, name="additive", cv=add_cv, gains=add_gains,
                    tone=ADD, norm=norm, label_soma=False)
    _draw_gain_tree(ax, x0=0.60, name="shunting", cv=shunt_cv,
                    gains=shunt_gains, tone=SHUNT, norm=norm, label_soma=True)

    # Paired seed-level result under the schematic (frozen aggregation).
    paired = path_gain_seed.copy()
    if "dataset" in paired:
        paired = paired[paired["dataset"] == "mnist"]
    if "ie_value" in paired:
        paired = paired[paired["ie_value"] == 5]
    pivot = paired.pivot_table(index="seed", columns="network_type",
                               values="path_gain_cv_mean",
                               aggfunc="mean").dropna()
    add_vals = pivot["dendritic_additive"].to_numpy(dtype=float)
    shunt_vals = pivot["dendritic_shunting"].to_numpy(dtype=float)
    means = [float(np.mean(add_vals)), float(np.mean(shunt_vals))]
    sds = [float(np.std(add_vals, ddof=1)) if len(add_vals) > 1 else 0.0,
           float(np.std(shunt_vals, ddof=1)) if len(shunt_vals) > 1 else 0.0]

    inset = ax.inset_axes([0.12, 0.0, 0.76, 0.20])
    style_panel(inset)
    inset.bar([0, 1], means, 0.56, yerr=sds, color=[ADD, SHUNT],
              edgecolor="white", linewidth=LW_HAIR,
              error_kw={"lw": LW_EDGE, "capthick": LW_EDGE}, capsize=2.0,
              zorder=2)
    for x, vals in ((0, add_vals), (1, shunt_vals)):
        if len(vals):
            jitter = np.linspace(-0.13, 0.13, len(vals))
            inset.scatter(np.full(len(vals), x) + jitter, vals, s=5.0,
                          facecolors="white", edgecolors=COLORS["edge"],
                          linewidths=LW_HAIR, zorder=3)
    inset.set_xlim(-0.55, 1.55)
    inset.set_ylim(0.0, 1.36)
    inset.set_xticks([0, 1])
    inset.set_xticklabels(["add.", "shunt."], fontsize=PT_SMALL)
    inset.set_yticks([0, 1])
    inset.set_yticklabels(["0", "1"], fontsize=PT_SMALL)
    inset.tick_params(length=1.8, width=LW_HAIR, pad=0.8)
    for spine in inset.spines.values():
        spine.set_linewidth(LW_HAIR)
    inset.set_ylabel("CV", fontsize=PT_SMALL, labelpad=1.0)

    print(f"[A] aggregate CV: additive={add_cv:.6f} shunting={shunt_cv:.6f}")
    print(f"[A] paired-seed CV (n={len(pivot)}): additive {means[0]:.6f}"
          f" +- {sds[0]:.6f}; shunting {means[1]:.6f} +- {sds[1]:.6f};"
          f" reduction {100.0 * (1.0 - means[1] / means[0]):.1f}%")


# ── panel B: stage-resolved submitted-field cosine ───────────────────────
def panel_field_cosine(ax, decomposition_runs):
    """B: MW-field cosine on distal/proximal stages (frozen aggregation).

    Filters, the checkpoint-first mean and the five-value assertion are
    ported verbatim from ``_plot_dendritic_feedback_fidelity``; the somatic
    stage stays excluded (cosine one by construction).
    """
    sub = decomposition_runs[
        (decomposition_runs["dataset"] == "mnist")
        & (decomposition_runs["strategy"] == "local_ca")
        & (decomposition_runs["rule_variant"] == "5f")
        & (decomposition_runs["error_broadcast_mode"] == "per_soma")
        & (decomposition_runs["scope_type"] == "stage")
        & (decomposition_runs["population"] == 0)
        & (decomposition_runs["stage_role"].isin(["distal", "proximal"]))
        & (decomposition_runs["family"] == "submitted_mw")
    ].copy()
    if sub.empty:
        raise ValueError(
            "Scope-corrected stage-resolved submitted-field data are "
            "unavailable")

    # Average train/validation/test batches within each checkpoint first, so
    # checkpoints -- not diagnostic batches -- remain the independent units.
    per_checkpoint = (
        sub.groupby(["run_name", "seed", "network_type", "stage_role"],
                    as_index=False)["cosine"].mean())

    stages = ["distal", "proximal"]
    cores = [("dendritic_additive", ADD), ("dendritic_shunting", SHUNT)]
    x = np.arange(len(stages), dtype=float)
    width = 0.34
    tops = {}
    for offset, (core, color) in zip([-width / 2, width / 2], cores):
        means, stds = [], []
        for stage in stages:
            values = per_checkpoint[
                (per_checkpoint["network_type"] == core)
                & (per_checkpoint["stage_role"] == stage)]["cosine"]
            if len(values) != 5:
                raise ValueError(
                    f"Expected five checkpoint values for {core}/{stage}, "
                    f"got {len(values)}")
            means.append(float(values.mean()))
            stds.append(float(values.std(ddof=1)))
        ax.bar(x + offset, means, width, yerr=stds, color=color,
               edgecolor="white", linewidth=LW_EDGE, capsize=ERR_CAPSIZE,
               error_kw={"lw": LW_ERR, "capthick": LW_ERR,
                         "ecolor": INK}, zorder=3)
        tops[core] = [m + s for m, s in zip(means, stds)]
        print(f"[B] {core}: distal {means[0]:.6f} +- {stds[0]:.6f}; "
              f"proximal {means[1]:.6f} +- {stds[1]:.6f}")

    # Direct color key in the data-free upper-left corner (no legend box).
    ax.text(-0.50, 0.288, "shunting", ha="left", va="top",
            fontsize=PT_LEGEND, color=SHUNT)
    ax.text(-0.50, 0.257, "additive", ha="left", va="top",
            fontsize=PT_LEGEND, color=ADD)

    ax.set_xticks(x)
    ax.set_xticklabels(stages)
    ax.set_xlim(-0.60, 1.60)
    ax.set_ylim(0.0, 0.30)
    ax.set_yticks([0.0, 0.1, 0.2, 0.3])
    ax.set_ylabel("MW-field cosine")


# ── panel C: post-training inhibition interventions ──────────────────────
INTERVENTION_ORDER = ["original", "zero_i", "shuffle_i", "mean_clamp_i",
                      "uniform_matched_i"]
INTERVENTION_LABEL = {
    "original": "learned",
    "zero_i": "zeroed",
    "shuffle_i": "shuffled",
    "mean_clamp_i": "batch mean",
    "uniform_matched_i": "uniform",
}
# Same house-palette keys the archived generator drew from: the learned
# model keeps the shunting green; the four ablations keep their distinct
# muted house tones so a bar can be traced across the two task groups.
INTERVENTION_COLOR = {
    "original": COLORS["shunting"],
    "zero_i": COLORS["mute"],
    "shuffle_i": COLORS["low_rank"],
    "mean_clamp_i": COLORS["per_soma"],
    "uniform_matched_i": COLORS["oracle"],
}
DATASET_ORDER = [("mnist", "MNIST"), ("noise_resilience", "noise")]


def panel_inhibition(ax, causal):
    """C: intervention accuracies (frozen aggregation and bar geometry)."""
    order = INTERVENTION_ORDER
    group_gap = 0.70
    width = 0.205

    centers = []
    for gi, (dataset, _label) in enumerate(DATASET_ORDER):
        center = gi * (len(order) * width + group_gap)
        centers.append(center)
        sub = causal[causal["dataset"] == dataset].copy()
        stats = (sub.groupby("intervention")["accuracy"]
                 .agg(["mean", "std"]).reindex(order))
        for ji, intervention in enumerate(order):
            xpos = center + (ji - (len(order) - 1) / 2) * width
            mean = 100.0 * float(stats.loc[intervention, "mean"])
            sd = 100.0 * float(stats.loc[intervention, "std"])
            ax.bar([xpos], [mean], width * 0.88, yerr=[sd],
                   color=INTERVENTION_COLOR[intervention],
                   edgecolor="white", linewidth=LW_HAIR, capsize=1.8,
                   error_kw={"lw": LW_ERR, "capthick": LW_ERR,
                             "ecolor": INK}, zorder=3)
            vals = 100.0 * sub[sub["intervention"] == intervention][
                "accuracy"].to_numpy(dtype=float)
            if vals.size:
                jitter = np.linspace(-0.062, 0.062, vals.size)
                ax.scatter(np.full(vals.size, xpos) + jitter, vals, s=4.5,
                           color="white", edgecolor=INK,
                           linewidth=LW_HAIR, zorder=5)
            if dataset == "mnist":
                # Direct per-bar labels replace the legend box; the noise
                # group repeats the same five interventions in this order.
                y_text = max(mean + sd, float(vals.max()) if vals.size
                             else 0.0) + 3.5
                ax.text(xpos, y_text, INTERVENTION_LABEL[intervention],
                        rotation=90, ha="center", va="bottom",
                        fontsize=PT_ANNOT,
                        color=INTERVENTION_COLOR[intervention], zorder=6)
            print(f"[C] {dataset}/{intervention}: {mean:.2f} +- {sd:.2f} % "
                  f"(n={vals.size})")

    ax.set_xticks(centers)
    ax.set_xticklabels([label for _dataset, label in DATASET_ORDER])
    ax.set_xlim(centers[0] - 0.66, centers[1] + 0.66)
    ax.set_ylim(0, 140)
    ax.set_yticks([0, 50, 100])
    ax.set_ylabel("accuracy (%)")
    ax.tick_params(axis="x", length=0)


# ── panels D, E: noise-resilience fidelity and learning sweeps ───────────
def _sweep(ax, frame, mean_col, std_col, *, linestyle, scale=1.0):
    """One core's line on an N_I sweep, mean +- 1 s.d. as whiskers."""
    for core in ("dendritic_shunting", "dendritic_additive"):
        sub = frame[frame["network_type"] == core].sort_values("ie_value")
        x = pd.to_numeric(sub["ie_value"], errors="coerce").to_numpy(float)
        y = scale * sub[mean_col].to_numpy(dtype=float)
        err = scale * sub[std_col].fillna(0.0).to_numpy(dtype=float)
        ax.errorbar(x, y, yerr=err, color=CORE_COLOR[core],
                    marker=CORE_MARKER[core], markerfacecolor="white",
                    markeredgecolor=CORE_COLOR[core], markeredgewidth=LW_ERR,
                    ms=MARKER_MS, lw=LW_DATA, linestyle=linestyle,
                    elinewidth=LW_ERR, capsize=ERR_CAPSIZE, zorder=4)
        yield core, x, y, err


def panel_fidelity(ax, summary):
    """D: submitted-field vs exact-transport cosine (frozen columns)."""
    noise = summary[summary["dataset"] == "noise_resilience"].copy()
    ends = {}
    for core, x, y, err in _sweep(ax, noise, "per_soma_weighted_cosine_mean",
                                  "per_soma_weighted_cosine_std",
                                  linestyle="-"):
        ends[core] = y[-1]
        print(f"[D] {core} MW cosine: ie0 {y[0]:.6f} +- {err[0]:.6f}; "
              f"ie40 {y[-1]:.6f} +- {err[-1]:.6f}")
    for core, x, y, err in _sweep(ax, noise,
                                  "path_transport_weighted_cosine_mean",
                                  "path_transport_weighted_cosine_std",
                                  linestyle="--"):
        print(f"[D] {core} exact-transport cosine: ie0 {y[0]:.6f} "
              f"+- {err[0]:.6f}; ie40 {y[-1]:.6f} +- {err[-1]:.6f}")

    # Condition annotations (linestyle key) and the figure's color/marker
    # key at the separated solid endpoints -- no legend box.
    ax.text(21.0, 0.88, "exact transport", ha="center", va="top",
            fontsize=PT_ANNOT, color=INK)
    ax.text(21.0, 0.33, "matched-width\nfallback", ha="center", va="bottom",
            fontsize=PT_ANNOT, color=INK)
    ax.text(42.5, ends["dendritic_shunting"], "shunting", ha="left",
            va="center", fontsize=PT_LEGEND, color=SHUNT)
    ax.text(42.5, ends["dendritic_additive"], "additive", ha="left",
            va="center", fontsize=PT_LEGEND, color=ADD)

    ax.set_xticks(IE_TICKS)
    ax.set_xlim(*IE_XLIM)
    ax.set_ylim(-0.10, 1.14)
    ax.set_yticks([0.0, 0.5, 1.0])
    ax.set_xlabel(IE_XLABEL)
    ax.set_ylabel("cosine")


def panel_learning(ax, summary, oracle_summary):
    """E: learning under MW fallback vs exact transported error."""
    baseline = summary[summary["dataset"] == "noise_resilience"].copy()
    oracle = oracle_summary[
        oracle_summary["dataset"] == "noise_resilience"].copy()
    for core, x, y, err in _sweep(ax, baseline, "test_accuracy_mean",
                                  "test_accuracy_std", linestyle="-",
                                  scale=100.0):
        print(f"[E] {core} MW accuracy: ie0 {y[0]:.3f} +- {err[0]:.3f}; "
              f"ie40 {y[-1]:.3f} +- {err[-1]:.3f} %")
    for core, x, y, err in _sweep(ax, oracle, "test_accuracy_mean",
                                  "test_accuracy_std", linestyle="--",
                                  scale=100.0):
        print(f"[E] {core} exact-transport accuracy: ie0 {y[0]:.3f} "
              f"+- {err[0]:.3f}; ie40 {y[-1]:.3f} +- {err[-1]:.3f} %")

    ax.text(24.0, 96.6, "exact transport", ha="center", va="bottom",
            fontsize=PT_ANNOT, color=INK)
    ax.text(24.0, 77.5, "matched-width\nfallback", ha="center", va="top",
            fontsize=PT_ANNOT, color=INK)

    ax.set_xticks(IE_TICKS)
    ax.set_xlim(*IE_XLIM)
    ax.set_ylim(44.0, 103.0)
    ax.set_yticks([50, 75, 100])
    ax.set_xlabel(IE_XLABEL)
    ax.set_ylabel("test accuracy (%)")


# ── the canvas ───────────────────────────────────────────────────────────
CANVAS_H_PT = 380.0


def build(path: Path = OUT):
    summary = _csv(SUMMARY_CSV)
    path_gain_seed = _csv(PATH_GAIN_SEED_CSV)
    oracle_summary = _csv(ORACLE_SUMMARY_CSV)
    decomposition_runs = _csv(DECOMPOSITION_RUNS_CSV)
    causal = _csv(INHIBITION_CAUSALITY_CSV)

    canvas = NativeCanvas(CANVAS_H_PT / 72.0, 2)
    ax_a = canvas.panel("path_gains", 0, 0, 4, schematic=True,
                        title="Path-gain field")
    ax_b = canvas.panel("field_cosine", 0, 4, 4, grid="y",
                        title="Stage-resolved cosine")
    ax_c = canvas.panel("inhibition", 0, 8, 4, grid="y",
                        title="Inhibition interventions")
    ax_d = canvas.panel("fidelity", 1, 0, 6, grid="y",
                        title="Feedback fidelity (noise task)")
    ax_e = canvas.panel("learning", 1, 6, 6, grid="y",
                        title="Learning (noise task)")

    panel_path_gains(ax_a, summary, path_gain_seed)
    panel_field_cosine(ax_b, decomposition_runs)
    panel_inhibition(ax_c, causal)
    panel_fidelity(ax_d, summary)
    panel_learning(ax_e, summary, oracle_summary)

    # Row 0 starts in three different grid columns, and the schematic panel
    # hangs no y decorations, so the measured column locks leave it a point
    # or two wider than its row-mates.  Measure after the first lock and top
    # the wide panels up with a declared right reserve so the row is exact.
    canvas.lock_reserves()
    row0 = ("path_gains", "field_cosine", "inhibition")
    widths = {name: canvas.axes[name].get_position().width * canvas.width_pt
              for name in row0}
    target = min(widths.values())
    for name in row0:
        extra = widths[name] - target
        if extra > 0.05:
            canvas.declare_reserve(name, right=extra)

    problems = canvas.save(path, name="figure_S01_panels_A-E")
    for problem in problems:
        print(f"    {problem}")
    return problems


if __name__ == "__main__":
    raise SystemExit(1 if build() else 0)
